foreach(_required_var IN ITEMS MONITOR_BINARY MAME_EXE MAME_STAGE_DIR MONITOR_OUTPUT_DIR)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "${_required_var} is required")
    endif()
endforeach()

get_filename_component(_monitor_binary "${MONITOR_BINARY}" ABSOLUTE)
get_filename_component(_mame_exe "${MAME_EXE}" ABSOLUTE)
get_filename_component(_monitor_output_dir "${MONITOR_OUTPUT_DIR}" ABSOLUTE)
get_filename_component(_stage_dir "${MAME_STAGE_DIR}" ABSOLUTE BASE_DIR "${_monitor_output_dir}")

if(NOT EXISTS "${_monitor_binary}")
    message(FATAL_ERROR "Monitor binary does not exist: ${_monitor_binary}")
endif()

if(NOT EXISTS "${_mame_exe}")
    message(FATAL_ERROR "MAME executable does not exist: ${_mame_exe}")
endif()

file(TO_CMAKE_PATH "${_monitor_output_dir}" _monitor_output_cmp)
file(TO_CMAKE_PATH "${_stage_dir}" _stage_cmp)

if("${_stage_cmp}" STREQUAL "${_monitor_output_cmp}")
    message(FATAL_ERROR "MAME stage directory must not be the monitor output directory")
endif()

string(APPEND _monitor_output_cmp "/")
string(APPEND _stage_cmp "/")
string(FIND "${_stage_cmp}" "${_monitor_output_cmp}" _stage_prefix)
if(NOT _stage_prefix EQUAL 0)
    message(FATAL_ERROR "MAME stage directory must be under the monitor output directory: ${_stage_dir}")
endif()

file(SIZE "${_monitor_binary}" _monitor_size)
if(NOT _monitor_size EQUAL 4096)
    message(FATAL_ERROR "Monitor ROM must be 4096 bytes, got ${_monitor_size}")
endif()

file(READ "${_monitor_binary}" _monitor_hex HEX)
math(EXPR _reset_hi_offset "(4096 - 2) * 2")
math(EXPR _reset_lo_offset "(4096 - 1) * 2")
string(SUBSTRING "${_monitor_hex}" ${_reset_hi_offset} 2 _reset_hi)
string(SUBSTRING "${_monitor_hex}" ${_reset_lo_offset} 2 _reset_lo)
set(_expected_pc "${_reset_hi}${_reset_lo}")
string(TOUPPER "${_expected_pc}" _expected_pc)

file(REMOVE_RECURSE "${_stage_dir}")
file(MAKE_DIRECTORY
    "${_stage_dir}/roms/m6805sbc"
    "${_stage_dir}/cfg"
)

configure_file("${_monitor_binary}" "${_stage_dir}/roms/m6805sbc/rom1.bin" COPYONLY)
file(WRITE "${_stage_dir}/cfg/m6805sbc.cfg"
    "<?xml version=\"1.0\"?>\r\n"
    "<!-- This file is generated by the monitor MAME test. -->\r\n"
    "<mameconfig version=\"10\">\r\n"
    "    <system name=\"m6805sbc\">\r\n"
    "        <input>\r\n"
    "            <port tag=\":BAUD\" type=\"DIPSWITCH\" mask=\"3\" defvalue=\"0\" value=\"0\" />\r\n"
    "        </input>\r\n"
    "    </system>\r\n"
    "</mameconfig>\r\n"
)

set(_reset_script "${_stage_dir}/reset_vector.lua")
file(WRITE "${_reset_script}"
    "local cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "print(string.format(\"RESET_PC=%04X\", cpu.state[\"PC\"].value))\r\n"
)

execute_process(
    COMMAND
        "${_mame_exe}"
        m6805sbc
        -rompath roms
        -cfg_directory cfg
        -homepath .
        -video none
        -sound none
        -skip_gameinfo
        -nothrottle
        -autoboot_delay 0
        -autoboot_script reset_vector.lua
        -seconds_to_run 1
    WORKING_DIRECTORY "${_stage_dir}"
    RESULT_VARIABLE _mame_result
    OUTPUT_VARIABLE _mame_stdout
    ERROR_VARIABLE _mame_stderr
)

set(_mame_output "${_mame_stdout}\n${_mame_stderr}")

if(NOT _mame_result EQUAL 0)
    message(FATAL_ERROR "MAME failed with exit code ${_mame_result}\n${_mame_output}")
endif()

string(REGEX MATCH "RESET_PC=([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])" _reset_match "${_mame_output}")
if(NOT _reset_match)
    message(FATAL_ERROR "MAME output did not report RESET_PC\n${_mame_output}")
endif()

set(_actual_pc "${CMAKE_MATCH_1}")
string(TOUPPER "${_actual_pc}" _actual_pc)

if(NOT _actual_pc STREQUAL _expected_pc)
    message(FATAL_ERROR "Expected reset PC ${_expected_pc}, got ${_actual_pc}\n${_mame_output}")
endif()
