if(NOT DEFINED MONITOR_SOURCE)
    message(FATAL_ERROR "MONITOR_SOURCE is required")
endif()

if(NOT EXISTS "${MONITOR_SOURCE}")
    message(FATAL_ERROR "monitor source does not exist: ${MONITOR_SOURCE}")
endif()

file(READ "${MONITOR_SOURCE}" source_hex HEX)
string(TOUPPER "${source_hex}" source_hex)
string(LENGTH "${source_hex}" hex_length)
math(EXPR byte_count "${hex_length} / 2")

set(errors "")
set(line_no 1)
set(column_no 1)
set(prev_byte "")
set(prev_prev_byte "")
set(in_single_quote FALSE)
set(in_double_quote FALSE)
set(in_comment FALSE)

if(byte_count GREATER 0)
    math(EXPR last_byte "${byte_count} - 1")
    foreach(byte_index RANGE 0 ${last_byte})
        math(EXPR hex_index "${byte_index} * 2")
        string(SUBSTRING "${source_hex}" ${hex_index} 2 byte)

        if(byte STREQUAL "0D")
            continue()
        endif()

        if(byte STREQUAL "0A")
            math(EXPR line_no "${line_no} + 1")
            set(column_no 1)
            set(prev_byte "")
            set(prev_prev_byte "")
            set(in_single_quote FALSE)
            set(in_double_quote FALSE)
            set(in_comment FALSE)
            continue()
        endif()

        if(byte STREQUAL "09")
            list(APPEND errors "TAB character at line ${line_no}, column ${column_no}")
        endif()

        if(NOT in_comment)
            if(byte STREQUAL "22" AND NOT in_single_quote)
                if(in_double_quote)
                    set(in_double_quote FALSE)
                else()
                    set(in_double_quote TRUE)
                endif()
            elseif(byte STREQUAL "27" AND NOT in_double_quote)
                if(in_single_quote)
                    set(in_single_quote FALSE)
                else()
                    set(in_single_quote TRUE)
                endif()
            elseif(byte STREQUAL "3B" AND NOT in_single_quote AND NOT in_double_quote)
                set(in_comment TRUE)
                if(column_no EQUAL 1 OR column_no EQUAL 41)
                    # Full-line comments start at column 1; running comments start at column 41.
                elseif(column_no GREATER 41)
                    math(EXPR source_end_column "${column_no} - 2")
                    if(NOT prev_byte STREQUAL "20" OR prev_prev_byte STREQUAL "20" OR NOT source_end_column GREATER 39)
                        list(APPEND errors
                            "comment at line ${line_no}, column ${column_no} must start in column 1, column 41, or exactly one space after source text longer than column 39"
                        )
                    endif()
                else()
                    list(APPEND errors
                        "comment at line ${line_no}, column ${column_no} must start in column 1 or column 41"
                    )
                endif()
            endif()
        endif()

        set(prev_prev_byte "${prev_byte}")
        set(prev_byte "${byte}")
        math(EXPR column_no "${column_no} + 1")
    endforeach()
endif()

if(errors)
    list(JOIN errors "\n  - " error_text)
    message(FATAL_ERROR "monitor.asm assembly style failed:\n  - ${error_text}")
endif()
