foreach(required_var IN ITEMS MONITOR_SOURCE MONITOR_SYMBOLS)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()

if(NOT EXISTS "${MONITOR_SOURCE}")
    message(FATAL_ERROR "monitor source does not exist: ${MONITOR_SOURCE}")
endif()

if(NOT EXISTS "${MONITOR_SYMBOLS}")
    message(FATAL_ERROR "monitor symbols do not exist: ${MONITOR_SYMBOLS}")
endif()

set(max_rom_code_end 0x1854)
set(errors "")

file(STRINGS "${MONITOR_SYMBOLS}" symbol_lines)
foreach(line IN LISTS symbol_lines)
    if(line MATCHES "^rom_code_end[ \t]+([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])")
        set(rom_code_end_hex "${CMAKE_MATCH_1}")
    endif()
endforeach()

if(NOT DEFINED rom_code_end_hex)
    list(APPEND errors "missing rom_code_end symbol")
else()
    math(EXPR rom_code_end_value "0x${rom_code_end_hex}")
    if(rom_code_end_value GREATER max_rom_code_end)
        list(APPEND errors "rom_code_end ${rom_code_end_hex} exceeds current monitor budget 1854")
    endif()
endif()

file(STRINGS "${MONITOR_SOURCE}" source_lines)

set(section "")
set(cpu_text_uses_msg_end FALSE)
set(cpu_text_has_nul FALSE)
set(boot_has_old_clear FALSE)
set(boot_has_old_position FALSE)
set(boot_has_default_erase FALSE)
set(boot_has_horizontal_position FALSE)

foreach(line IN LISTS source_lines)
    if(line MATCHES "^cpu_row_text:")
        set(section "cpu")
    elseif(line MATCHES "^op_adc_imm")
        set(section "")
    elseif(line MATCHES "^boot_screen_text:")
        set(section "boot")
    elseif(line MATCHES "^rom_code_end:")
        set(section "")
    endif()

    if(section STREQUAL "cpu")
        if(line MATCHES "\\.byte.*NUL")
            set(cpu_text_has_nul TRUE)
        endif()
        if(line MATCHES "msg_end")
            set(cpu_text_uses_msg_end TRUE)
        endif()
    elseif(section STREQUAL "boot")
        if(line MATCHES "\\.text[ \t]+\"\\[2J\"")
            set(boot_has_old_clear TRUE)
        endif()
        if(line MATCHES "\\.text[ \t]+\"\\[1;68H\"")
            set(boot_has_old_position TRUE)
        endif()
        if(line MATCHES "\\.text[ \t]+\"\\[J\"")
            set(boot_has_default_erase TRUE)
        endif()
        if(line MATCHES "\\.text[ \t]+\"\\[68G\"")
            set(boot_has_horizontal_position TRUE)
        endif()
    endif()
endforeach()

if(cpu_text_has_nul)
    list(APPEND errors "CPU/status text fragments should use high-bit terminators, not NUL bytes")
endif()

if(NOT cpu_text_uses_msg_end)
    list(APPEND errors "CPU/status text fragments should mark final bytes with msg_end")
endif()

if(boot_has_old_clear)
    list(APPEND errors "boot clear sequence should use ESC[J default erase instead of ESC[2J")
endif()

if(boot_has_old_position)
    list(APPEND errors "boot version positioning should use horizontal position ESC[68G after HOME")
endif()

if(NOT boot_has_default_erase)
    list(APPEND errors "boot text should include ESC[J default erase")
endif()

if(NOT boot_has_horizontal_position)
    list(APPEND errors "boot text should include ESC[68G horizontal position")
endif()

if(errors)
    string(REPLACE ";" "\n  - " error_text "${errors}")
    message(FATAL_ERROR "monitor table encoding failed:\n  - ${error_text}")
endif()
