foreach(_required_var IN ITEMS MONITOR_BINARY MONITOR_SYMBOLS MAME_EXE MAME_STAGE_DIR MONITOR_OUTPUT_DIR)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "${_required_var} is required")
    endif()
endforeach()

set(USER_CODE 0x0400)
set(USER_PC_AFTER_SWI "0409")
set(EXPECTED_A "00")
set(EXPECTED_X "34")
set(EXPECTED_CC "0B")
set(EXPECTED_SP "7A")
set(STOP_SWI "03")

get_filename_component(_monitor_binary "${MONITOR_BINARY}" ABSOLUTE)
get_filename_component(_monitor_symbols "${MONITOR_SYMBOLS}" ABSOLUTE)
get_filename_component(_mame_exe "${MAME_EXE}" ABSOLUTE)
get_filename_component(_monitor_output_dir "${MONITOR_OUTPUT_DIR}" ABSOLUTE)
get_filename_component(_stage_dir "${MAME_STAGE_DIR}" ABSOLUTE BASE_DIR "${_monitor_output_dir}")

foreach(_path_var IN ITEMS _monitor_binary _monitor_symbols _mame_exe)
    if(NOT EXISTS "${${_path_var}}")
        message(FATAL_ERROR "required input does not exist: ${${_path_var}}")
    endif()
endforeach()

file(TO_CMAKE_PATH "${_monitor_output_dir}" _monitor_output_cmp)
file(TO_CMAKE_PATH "${_stage_dir}" _stage_cmp)

if("${_stage_cmp}" STREQUAL "${_monitor_output_cmp}")
    message(FATAL_ERROR "MAME stage directory must not be the monitor output directory")
endif()

string(APPEND _monitor_output_cmp "/")
string(APPEND _stage_cmp "/")
string(FIND "${_stage_cmp}" "${_monitor_output_cmp}" _stage_prefix)
if(NOT _stage_prefix EQUAL 0)
    message(FATAL_ERROR "MAME stage directory must be under the monitor output directory: ${_stage_dir}")
endif()

function(_require_symbol _name)
    if(NOT DEFINED "SYM_${_name}")
        message(FATAL_ERROR "Missing symbol '${_name}' in ${_monitor_symbols}")
    endif()
endfunction()

file(STRINGS "${_monitor_symbols}" _symbol_lines)
foreach(_line IN LISTS _symbol_lines)
    if(_line MATCHES "^([A-Za-z_][A-Za-z0-9_]*)[ \t]+([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])")
        string(TOUPPER "${CMAKE_MATCH_2}" _symbol_value)
        set("SYM_${CMAKE_MATCH_1}" "${_symbol_value}")
    endif()
endforeach()

foreach(_symbol IN ITEMS
        idle
        saved_sp
        saved_pc_hi
        saved_pc_lo
        saved_a
        saved_x
        saved_cc
        stop_rsn)
    _require_symbol("${_symbol}")
endforeach()

file(REMOVE_RECURSE "${_stage_dir}")
file(MAKE_DIRECTORY
    "${_stage_dir}/roms/m6805sbc"
    "${_stage_dir}/cfg"
)

configure_file("${_monitor_binary}" "${_stage_dir}/roms/m6805sbc/rom1.bin" COPYONLY)
file(WRITE "${_stage_dir}/cfg/m6805sbc.cfg"
    "<?xml version=\"1.0\"?>\r\n"
    "<!-- This file is generated by the monitor MAME test. -->\r\n"
    "<mameconfig version=\"10\">\r\n"
    "    <system name=\"m6805sbc\">\r\n"
    "        <input>\r\n"
    "            <port tag=\":BAUD\" type=\"DIPSWITCH\" mask=\"3\" defvalue=\"0\" value=\"0\" />\r\n"
    "        </input>\r\n"
    "    </system>\r\n"
    "</mameconfig>\r\n"
)

set(_swi_script "${_stage_dir}/swi_entry.lua")
file(WRITE "${_swi_script}"
    "local idle = 0x${SYM_idle}\r\n"
    "local user_code = ${USER_CODE}\r\n"
    "local frames = 0\r\n"
    "local phase = \"wait_reset\"\r\n"
    "local cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "local mem = cpu.spaces[\"program\"]\r\n"
    "local program = {0xae, 0x34, 0xa6, 0x00, 0x98, 0x9a, 0x99, 0x9b, 0x83}\r\n"
    "local function load_program()\r\n"
    "    for index, byte in ipairs(program) do mem:write_u8(user_code + index - 1, byte) end\r\n"
    "end\r\n"
    "emu.register_frame_done(function()\r\n"
    "    frames = frames + 1\r\n"
    "    cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "    mem = cpu.spaces[\"program\"]\r\n"
    "    if phase == \"wait_reset\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 60 then return end\r\n"
    "        load_program()\r\n"
    "        cpu.state[\"PC\"].value = user_code\r\n"
    "        phase = \"wait_swi\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_swi\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 120 then return end\r\n"
    "        print(string.format(\"SWI_ENTRY PC=%04X S=%02X SAVED_SP=%02X SAVED_PC=%02X%02X SAVED_A=%02X SAVED_X=%02X SAVED_CC=%02X STOP=%02X\", cpu.state[\"PC\"].value, cpu.state[\"S\"].value, mem:read_u8(0x${SYM_saved_sp}), mem:read_u8(0x${SYM_saved_pc_hi}), mem:read_u8(0x${SYM_saved_pc_lo}), mem:read_u8(0x${SYM_saved_a}), mem:read_u8(0x${SYM_saved_x}), mem:read_u8(0x${SYM_saved_cc}), mem:read_u8(0x${SYM_stop_rsn})))\r\n"
    "        manager.machine:exit()\r\n"
    "        return\r\n"
    "    end\r\n"
    "end, \"swi_entry\")\r\n"
)

execute_process(
    COMMAND
        "${_mame_exe}"
        m6805sbc
        -rompath roms
        -cfg_directory cfg
        -homepath .
        -video none
        -sound none
        -skip_gameinfo
        -nothrottle
        -autoboot_delay 0
        -autoboot_script swi_entry.lua
        -seconds_to_run 3
    WORKING_DIRECTORY "${_stage_dir}"
    RESULT_VARIABLE _mame_result
    OUTPUT_VARIABLE _mame_stdout
    ERROR_VARIABLE _mame_stderr
)

set(_mame_output "${_mame_stdout}\n${_mame_stderr}")

if(NOT _mame_result EQUAL 0)
    message(FATAL_ERROR "MAME failed with exit code ${_mame_result}\n${_mame_output}")
endif()

string(REGEX MATCH "SWI_ENTRY " _state_match "${_mame_output}")
if(NOT _state_match)
    message(FATAL_ERROR "MAME output did not report SWI_ENTRY\n${_mame_output}")
endif()

function(_capture_hex _out_var _pattern _description)
    string(REGEX MATCH "${_pattern}" _field_match "${_mame_output}")
    if(NOT _field_match)
        message(FATAL_ERROR "MAME output did not report ${_description}\n${_mame_output}")
    endif()

    string(TOUPPER "${CMAKE_MATCH_1}" _captured)
    set(${_out_var} "${_captured}" PARENT_SCOPE)
endfunction()

_capture_hex(_actual_pc "SWI_ENTRY PC=([0-9A-Fa-f]+)" "PC")
_capture_hex(_actual_s " S=([0-9A-Fa-f]+)" "stack pointer")
_capture_hex(_actual_saved_sp " SAVED_SP=([0-9A-Fa-f]+)" "saved SP")
_capture_hex(_actual_saved_pc " SAVED_PC=([0-9A-Fa-f]+)" "saved PC")
_capture_hex(_actual_saved_a " SAVED_A=([0-9A-Fa-f]+)" "saved A")
_capture_hex(_actual_saved_x " SAVED_X=([0-9A-Fa-f]+)" "saved X")
_capture_hex(_actual_saved_cc " SAVED_CC=([0-9A-Fa-f]+)" "saved CC")
_capture_hex(_actual_stop " STOP=([0-9A-Fa-f]+)" "stop reason")

foreach(_expected_pair IN ITEMS
        "_actual_pc;${SYM_idle};PC at idle"
        "_actual_s;7F;live stack reset for monitor"
        "_actual_saved_sp;${EXPECTED_SP};saved post-SWI stack pointer"
        "_actual_saved_pc;${USER_PC_AFTER_SWI};saved PC after SWI"
        "_actual_saved_a;${EXPECTED_A};saved A"
        "_actual_saved_x;${EXPECTED_X};saved X"
        "_actual_saved_cc;${EXPECTED_CC};saved condition codes"
        "_actual_stop;${STOP_SWI};stop reason")
    string(REPLACE ";" "|" _encoded "${_expected_pair}")
    string(REPLACE "|" ";" _fields "${_encoded}")
    list(GET _fields 0 _var)
    list(GET _fields 1 _expected)
    list(GET _fields 2 _description)
    if(NOT "${${_var}}" STREQUAL "${_expected}")
        message(FATAL_ERROR "Expected ${_description} ${_expected}, got ${${_var}}\n${_mame_output}")
    endif()
endforeach()
