foreach(_required_var IN ITEMS MONITOR_BINARY MONITOR_SYMBOLS BREAKPOINT_TEST_BINARY MAME_EXE MAME_STAGE_DIR MONITOR_OUTPUT_DIR)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "${_required_var} is required")
    endif()
endforeach()

set(PROGRAM_START 0x0110)
set(BREAK1_ADDR 0x0112)
set(BREAK2_ADDR 0x011C)
set(BREAK1_OPCODE "A6")
set(BREAK2_OPCODE "AE")
set(PATCH_OPCODE "83")
set(EXPECTED_A "56")
set(EXPECTED_X_BEFORE "34")
set(EXPECTED_SP "7A")
set(STOP_BREAK "05")

get_filename_component(_monitor_binary "${MONITOR_BINARY}" ABSOLUTE)
get_filename_component(_monitor_symbols "${MONITOR_SYMBOLS}" ABSOLUTE)
get_filename_component(_breakpoint_test_binary "${BREAKPOINT_TEST_BINARY}" ABSOLUTE)
get_filename_component(_mame_exe "${MAME_EXE}" ABSOLUTE)
get_filename_component(_monitor_output_dir "${MONITOR_OUTPUT_DIR}" ABSOLUTE)
get_filename_component(_stage_dir "${MAME_STAGE_DIR}" ABSOLUTE BASE_DIR "${_monitor_output_dir}")

foreach(_path_var IN ITEMS _monitor_binary _monitor_symbols _breakpoint_test_binary _mame_exe)
    if(NOT EXISTS "${${_path_var}}")
        message(FATAL_ERROR "required input does not exist: ${${_path_var}}")
    endif()
endforeach()

function(_binary_as_lua _out_var _path)
    file(READ "${_path}" _bytes_hex HEX)
    string(REGEX REPLACE "([0-9A-Fa-f][0-9A-Fa-f])" "0x\\1;" _byte_list "${_bytes_hex}")
    string(REGEX REPLACE ";$" "" _byte_list "${_byte_list}")
    string(REPLACE ";" ", " _lua_bytes "${_byte_list}")
    set(${_out_var} "${_lua_bytes}" PARENT_SCOPE)
endfunction()

_binary_as_lua(_breakpoint_program "${_breakpoint_test_binary}")

file(TO_CMAKE_PATH "${_monitor_output_dir}" _monitor_output_cmp)
file(TO_CMAKE_PATH "${_stage_dir}" _stage_cmp)

if("${_stage_cmp}" STREQUAL "${_monitor_output_cmp}")
    message(FATAL_ERROR "MAME stage directory must not be the monitor output directory")
endif()

string(APPEND _monitor_output_cmp "/")
string(APPEND _stage_cmp "/")
string(FIND "${_stage_cmp}" "${_monitor_output_cmp}" _stage_prefix)
if(NOT _stage_prefix EQUAL 0)
    message(FATAL_ERROR "MAME stage directory must be under the monitor output directory: ${_stage_dir}")
endif()

function(_require_symbol _name)
    if(NOT DEFINED "SYM_${_name}")
        message(FATAL_ERROR "Missing symbol '${_name}' in ${_monitor_symbols}")
    endif()
endfunction()

file(STRINGS "${_monitor_symbols}" _symbol_lines)
foreach(_line IN LISTS _symbol_lines)
    if(_line MATCHES "^([A-Za-z_][A-Za-z0-9_]*)[ \t]+([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])")
        string(TOUPPER "${CMAKE_MATCH_2}" _symbol_value)
        set("SYM_${CMAKE_MATCH_1}" "${_symbol_value}")
    endif()
endforeach()

foreach(_symbol IN ITEMS
        idle
        bp_set
        bp_cont
        bp_tbl
        saved_sp
        saved_pc_hi
        saved_pc_lo
        saved_a
        saved_x
        saved_cc
        stop_rsn
        tmr_vec_hi
        tmr_vec_lo
        tmr_def_hdlr)
    _require_symbol("${_symbol}")
endforeach()

file(REMOVE_RECURSE "${_stage_dir}")
file(MAKE_DIRECTORY
    "${_stage_dir}/roms/m6805sbc"
    "${_stage_dir}/cfg"
)

configure_file("${_monitor_binary}" "${_stage_dir}/roms/m6805sbc/rom1.bin" COPYONLY)
file(WRITE "${_stage_dir}/cfg/m6805sbc.cfg"
    "<?xml version=\"1.0\"?>\r\n"
    "<!-- This file is generated by the monitor MAME test. -->\r\n"
    "<mameconfig version=\"10\">\r\n"
    "    <system name=\"m6805sbc\">\r\n"
    "        <input>\r\n"
    "            <port tag=\":BAUD\" type=\"DIPSWITCH\" mask=\"3\" defvalue=\"0\" value=\"0\" />\r\n"
    "        </input>\r\n"
    "    </system>\r\n"
    "</mameconfig>\r\n"
)

set(_breakpoint_script "${_stage_dir}/breakpoint.lua")
file(WRITE "${_breakpoint_script}"
    "local idle = 0x${SYM_idle}\r\n"
    "local bp_set = 0x${SYM_bp_set}\r\n"
    "local bp_cont = 0x${SYM_bp_cont}\r\n"
    "local bp_tbl = 0x${SYM_bp_tbl}\r\n"
    "local program_start = ${PROGRAM_START}\r\n"
    "local break1_addr = ${BREAK1_ADDR}\r\n"
    "local break2_addr = ${BREAK2_ADDR}\r\n"
    "local frames = 0\r\n"
    "local phase = \"wait_reset\"\r\n"
    "local armed = {}\r\n"
    "local first = {}\r\n"
    "local second = {}\r\n"
    "local cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "local mem = cpu.spaces[\"program\"]\r\n"
    "local function write_word(high_addr, low_addr, value)\r\n"
    "    mem:write_u8(high_addr, math.floor(value / 256))\r\n"
    "    mem:write_u8(low_addr, value % 256)\r\n"
    "end\r\n"
    "local function read_word(high_addr, low_addr)\r\n"
    "    return mem:read_u8(high_addr) * 256 + mem:read_u8(low_addr)\r\n"
    "end\r\n"
    "local function load_program()\r\n"
    "    local program = { ${_breakpoint_program} }\r\n"
    "    for index, byte in ipairs(program) do mem:write_u8(program_start + index - 1, byte) end\r\n"
    "end\r\n"
    "emu.register_frame_done(function()\r\n"
    "    frames = frames + 1\r\n"
    "    cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "    mem = cpu.spaces[\"program\"]\r\n"
    "    if phase == \"wait_reset\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 60 then return end\r\n"
    "        load_program()\r\n"
    "        write_word(bp_tbl, bp_tbl + 1, break1_addr)\r\n"
    "        write_word(bp_tbl + 3, bp_tbl + 4, break2_addr)\r\n"
    "        cpu.state[\"PC\"].value = bp_set\r\n"
    "        phase = \"wait_set\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_set\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 120 then return end\r\n"
    "        armed.patch1 = mem:read_u8(break1_addr)\r\n"
    "        armed.patch2 = mem:read_u8(break2_addr)\r\n"
    "        armed.orig1 = mem:read_u8(bp_tbl + 2)\r\n"
    "        armed.orig2 = mem:read_u8(bp_tbl + 5)\r\n"
    "        cpu.state[\"A\"].value = 0x12\r\n"
    "        cpu.state[\"X\"].value = 0x00\r\n"
    "        cpu.state[\"S\"].value = 0x7f\r\n"
    "        cpu.state[\"PC\"].value = program_start\r\n"
    "        phase = \"wait_first_break\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_first_break\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 240 then return end\r\n"
    "        first.saved_pc = read_word(0x${SYM_saved_pc_hi}, 0x${SYM_saved_pc_lo})\r\n"
    "        first.saved_a = mem:read_u8(0x${SYM_saved_a})\r\n"
    "        first.saved_x = mem:read_u8(0x${SYM_saved_x})\r\n"
    "        first.saved_sp = mem:read_u8(0x${SYM_saved_sp})\r\n"
    "        first.stop = mem:read_u8(0x${SYM_stop_rsn})\r\n"
    "        first.restored1 = mem:read_u8(break1_addr)\r\n"
    "        first.patch2 = mem:read_u8(break2_addr)\r\n"
    "        cpu.state[\"S\"].value = 0x${EXPECTED_SP}\r\n"
    "        cpu.state[\"PC\"].value = bp_cont\r\n"
    "        phase = \"wait_second_break\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_second_break\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 360 then return end\r\n"
    "        second.saved_pc = read_word(0x${SYM_saved_pc_hi}, 0x${SYM_saved_pc_lo})\r\n"
    "        second.saved_a = mem:read_u8(0x${SYM_saved_a})\r\n"
    "        second.saved_x = mem:read_u8(0x${SYM_saved_x})\r\n"
    "        second.saved_sp = mem:read_u8(0x${SYM_saved_sp})\r\n"
    "        second.stop = mem:read_u8(0x${SYM_stop_rsn})\r\n"
    "        second.patch1 = mem:read_u8(break1_addr)\r\n"
    "        second.restored2 = mem:read_u8(break2_addr)\r\n"
    "        second.timer_vec = read_word(0x${SYM_tmr_vec_hi}, 0x${SYM_tmr_vec_lo})\r\n"
    "        print(string.format(\"BREAKPOINT PATCH1=%02X PATCH2=%02X ORIG1=%02X ORIG2=%02X FIRST_PC=%04X FIRST_A=%02X FIRST_X=%02X FIRST_SP=%02X FIRST_STOP=%02X RESTORED1=%02X FIRST_PATCH2=%02X SECOND_PC=%04X SECOND_A=%02X SECOND_X=%02X SECOND_SP=%02X SECOND_STOP=%02X SECOND_PATCH1=%02X RESTORED2=%02X TIMER_VEC=%04X\", armed.patch1, armed.patch2, armed.orig1, armed.orig2, first.saved_pc, first.saved_a, first.saved_x, first.saved_sp, first.stop, first.restored1, first.patch2, second.saved_pc, second.saved_a, second.saved_x, second.saved_sp, second.stop, second.patch1, second.restored2, second.timer_vec))\r\n"
    "        manager.machine:exit()\r\n"
    "        return\r\n"
    "    end\r\n"
    "end, \"breakpoint\")\r\n"
)

execute_process(
    COMMAND
        "${_mame_exe}"
        m6805sbc
        -rompath roms
        -cfg_directory cfg
        -homepath .
        -video none
        -sound none
        -skip_gameinfo
        -nothrottle
        -autoboot_delay 0
        -autoboot_script breakpoint.lua
        -seconds_to_run 5
    WORKING_DIRECTORY "${_stage_dir}"
    RESULT_VARIABLE _mame_result
    OUTPUT_VARIABLE _mame_stdout
    ERROR_VARIABLE _mame_stderr
)

set(_mame_output "${_mame_stdout}\n${_mame_stderr}")

if(NOT _mame_result EQUAL 0)
    message(FATAL_ERROR "MAME failed with exit code ${_mame_result}\n${_mame_output}")
endif()

string(REGEX MATCH "BREAKPOINT " _state_match "${_mame_output}")
if(NOT _state_match)
    message(FATAL_ERROR "MAME output did not report BREAKPOINT\n${_mame_output}")
endif()

function(_capture_hex _out_var _pattern _description)
    string(REGEX MATCH "${_pattern}" _field_match "${_mame_output}")
    if(NOT _field_match)
        message(FATAL_ERROR "MAME output did not report ${_description}\n${_mame_output}")
    endif()

    string(TOUPPER "${CMAKE_MATCH_1}" _captured)
    set(${_out_var} "${_captured}" PARENT_SCOPE)
endfunction()

_capture_hex(_patch1 "PATCH1=([0-9A-Fa-f]+)" "first patched breakpoint opcode")
_capture_hex(_patch2 " PATCH2=([0-9A-Fa-f]+)" "second patched breakpoint opcode")
_capture_hex(_orig1 " ORIG1=([0-9A-Fa-f]+)" "first original breakpoint opcode")
_capture_hex(_orig2 " ORIG2=([0-9A-Fa-f]+)" "second original breakpoint opcode")
_capture_hex(_first_pc " FIRST_PC=([0-9A-Fa-f]+)" "first breakpoint saved PC")
_capture_hex(_first_a " FIRST_A=([0-9A-Fa-f]+)" "first breakpoint saved A")
_capture_hex(_first_x " FIRST_X=([0-9A-Fa-f]+)" "first breakpoint saved X")
_capture_hex(_first_sp " FIRST_SP=([0-9A-Fa-f]+)" "first breakpoint saved SP")
_capture_hex(_first_stop " FIRST_STOP=([0-9A-Fa-f]+)" "first breakpoint stop reason")
_capture_hex(_restored1 " RESTORED1=([0-9A-Fa-f]+)" "first restored breakpoint opcode")
_capture_hex(_first_patch2 " FIRST_PATCH2=([0-9A-Fa-f]+)" "second opcode during first break")
_capture_hex(_second_pc " SECOND_PC=([0-9A-Fa-f]+)" "second breakpoint saved PC")
_capture_hex(_second_a " SECOND_A=([0-9A-Fa-f]+)" "second breakpoint saved A")
_capture_hex(_second_x " SECOND_X=([0-9A-Fa-f]+)" "second breakpoint saved X")
_capture_hex(_second_sp " SECOND_SP=([0-9A-Fa-f]+)" "second breakpoint saved SP")
_capture_hex(_second_stop " SECOND_STOP=([0-9A-Fa-f]+)" "second breakpoint stop reason")
_capture_hex(_second_patch1 " SECOND_PATCH1=([0-9A-Fa-f]+)" "first opcode during second break")
_capture_hex(_restored2 " RESTORED2=([0-9A-Fa-f]+)" "second restored breakpoint opcode")
_capture_hex(_timer_vec " TIMER_VEC=([0-9A-Fa-f]+)" "restored timer vector")

foreach(_expected_pair IN ITEMS
        "_patch1;${PATCH_OPCODE};first patched breakpoint opcode"
        "_patch2;${PATCH_OPCODE};second patched breakpoint opcode"
        "_orig1;${BREAK1_OPCODE};first recorded original opcode"
        "_orig2;${BREAK2_OPCODE};second recorded original opcode"
        "_first_pc;0112;first saved PC at breakpoint address"
        "_first_a;12;first saved A before breakpoint instruction"
        "_first_x;${EXPECTED_X_BEFORE};first saved X before breakpoint instruction"
        "_first_sp;${EXPECTED_SP};first saved breakpoint stack pointer"
        "_first_stop;${STOP_BREAK};first breakpoint stop reason"
        "_restored1;${BREAK1_OPCODE};first restored opcode after breakpoint hit"
        "_first_patch2;${PATCH_OPCODE};second breakpoint remains armed after first hit"
        "_second_pc;011C;second saved PC at breakpoint address"
        "_second_a;${EXPECTED_A};second saved A after first continued instruction"
        "_second_x;${EXPECTED_X_BEFORE};second saved X after first continued instruction"
        "_second_sp;${EXPECTED_SP};second saved breakpoint stack pointer"
        "_second_stop;${STOP_BREAK};second breakpoint stop reason"
        "_second_patch1;${PATCH_OPCODE};first breakpoint re-armed after continue"
        "_restored2;${BREAK2_OPCODE};second restored opcode after breakpoint hit"
        "_timer_vec;${SYM_tmr_def_hdlr};restored timer vector")
    string(REPLACE ";" "|" _encoded "${_expected_pair}")
    string(REPLACE "|" ";" _fields "${_encoded}")
    list(GET _fields 0 _var)
    list(GET _fields 1 _expected)
    list(GET _fields 2 _description)
    if(NOT "${${_var}}" STREQUAL "${_expected}")
        message(FATAL_ERROR "Expected ${_description} ${_expected}, got ${${_var}}\n${_mame_output}")
    endif()
endforeach()
