foreach(_required_var IN ITEMS TASM_TABLE DISASSEMBLY_EXPECTED)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "${_required_var} is required")
    endif()
endforeach()

foreach(_path_var IN ITEMS TASM_TABLE DISASSEMBLY_EXPECTED)
    if(NOT EXISTS "${${_path_var}}")
        message(FATAL_ERROR "required input does not exist: ${${_path_var}}")
    endif()
endforeach()

function(_canon _input _output)
    string(TOLOWER "${_input}" _name)

    if(_name STREQUAL "bhs")
        set(_name "bcc")
    elseif(_name STREQUAL "blo")
        set(_name "bcs")
    elseif(_name STREQUAL "cmpx")
        set(_name "cpx")
    elseif(_name STREQUAL "dex")
        set(_name "decx")
    elseif(_name STREQUAL "inx")
        set(_name "incx")
    elseif(_name STREQUAL "lsl")
        set(_name "asl")
    elseif(_name STREQUAL "lsla")
        set(_name "asla")
    elseif(_name STREQUAL "lslx")
        set(_name "aslx")
    endif()

    set(${_output} "${_name}" PARENT_SCOPE)
endfunction()

function(_hex2 _value _output)
    string(TOUPPER "${_value}" _hex)
    string(LENGTH "${_hex}" _len)

    if(_len EQUAL 1)
        set(_hex "0${_hex}")
    endif()

    set(${_output} "${_hex}" PARENT_SCOPE)
endfunction()

function(_need _opcode _mode _mnemonic _why)
    _hex2("${_opcode}" _op)
    string(TOLOWER "${_mnemonic}" _mn)
    set(_sig "${_op}|${_mode}|${_mn}")
    list(FIND fixture_sigs "${_sig}" _sig_index)

    if(_sig_index EQUAL -1)
        list(APPEND missing "${_why}: opcode $${_op}, mode ${_mode}, mnemonic ${_mn}")
        set(missing "${missing}" PARENT_SCOPE)
    endif()
endfunction()

set(fixture_sigs "")
set(has_invalid FALSE)
set(has_trunc_fffe FALSE)
set(has_trunc_ffff FALSE)

file(STRINGS "${DISASSEMBLY_EXPECTED}" _expected_lines)
foreach(_line IN LISTS _expected_lines)
    string(LENGTH "${_line}" _line_len)
    if(_line_len LESS 23)
        message(FATAL_ERROR "cannot parse disassembly fixture row: '${_line}'")
    endif()

    string(SUBSTRING "${_line}" 1 4 _addr)
    string(SUBSTRING "${_line}" 7 2 _op)
    string(SUBSTRING "${_line}" 19 5 _mn)
    if(_line_len GREATER 27)
        string(SUBSTRING "${_line}" 27 -1 _operand)
    else()
        set(_operand "")
    endif()

    if(NOT _addr MATCHES "^[0-9A-F][0-9A-F][0-9A-F][0-9A-F]$" OR NOT _op MATCHES "^[0-9A-F][0-9A-F]$")
        message(FATAL_ERROR "cannot parse disassembly fixture row: '${_line}'")
    endif()

    string(STRIP "${_mn}" _mn)
    string(STRIP "${_operand}" _operand)
    string(TOLOWER "${_operand}" _operand)

    if(_mn STREQUAL "fcb")
        if(_addr STREQUAL "0228" AND _op STREQUAL "31")
            set(has_invalid TRUE)
        elseif(_addr STREQUAL "1FFE")
            set(has_trunc_fffe TRUE)
        elseif(_addr STREQUAL "1FFF")
            set(has_trunc_ffff TRUE)
        endif()
        continue()
    endif()

    if(_operand STREQUAL "")
        set(_mode "inh")
    elseif(_operand MATCHES "^#")
        set(_mode "imm")
    elseif(_operand STREQUAL ",x")
        set(_mode "idx")
    elseif(_operand MATCHES "^\\$[0-9a-f][0-9a-f],x$")
        set(_mode "idx8")
    elseif(_operand MATCHES "^\\$[0-9a-f][0-9a-f][0-9a-f][0-9a-f],x$")
        set(_mode "idx16")
    elseif(_operand MATCHES "^[0-7],\\$[0-9a-f][0-9a-f],\\$[0-9a-f][0-9a-f][0-9a-f][0-9a-f]$")
        set(_mode "bitrel")
    elseif(_operand MATCHES "^[0-7],\\$[0-9a-f][0-9a-f]$")
        set(_mode "bit")
    elseif(_operand MATCHES "^\\$[0-9a-f][0-9a-f]$")
        set(_mode "dir")
    elseif(_operand MATCHES "^\\$[0-9a-f][0-9a-f][0-9a-f][0-9a-f]$")
        math(EXPR _op_value "0x${_op}")
        if((_op_value GREATER_EQUAL 0x20 AND _op_value LESS_EQUAL 0x2f) OR _op_value EQUAL 0xad)
            set(_mode "rel")
        else()
            set(_mode "ext")
        endif()
    else()
        message(FATAL_ERROR "cannot classify disassembly operand '${_operand}' in '${_line}'")
    endif()

    list(APPEND fixture_sigs "${_op}|${_mode}|${_mn}")
endforeach()

set(missing "")

file(STRINGS "${TASM_TABLE}" _tasm_lines)
foreach(_line IN LISTS _tasm_lines)
    string(REGEX REPLACE "/\\*.*$" "" _line "${_line}")
    string(STRIP "${_line}" _line)

    if(NOT _line MATCHES "^([A-Z0-9]+)[ \t]+([^ \t]+)[ \t]+([0-9A-F][0-9A-F])[ \t]+([0-9]+)[ \t]+([A-Z0-9]+)")
        continue()
    endif()

    set(_mn_raw "${CMAKE_MATCH_1}")
    set(_args "${CMAKE_MATCH_2}")
    set(_opcode "${CMAKE_MATCH_3}")
    set(_bytes "${CMAKE_MATCH_4}")
    set(_mod "${CMAKE_MATCH_5}")
    _canon("${_mn_raw}" _mn)

    if(_mod STREQUAL "MBIT")
        string(SUBSTRING "${_opcode}" 0 1 _op_hi)
        string(SUBSTRING "${_opcode}" 1 1 _op_lo)
        if(_op_lo STREQUAL "0")
            set(_bit_ops "0" "2" "4" "6" "8" "A" "C" "E")
        else()
            set(_bit_ops "1" "3" "5" "7" "9" "B" "D" "F")
        endif()

        foreach(_bit_op_lo IN LISTS _bit_ops)
            set(_bit_op "${_op_hi}${_bit_op_lo}")
            if(_args STREQUAL "*,*")
                _need("${_bit_op}" "bit" "${_mn}" "${_mn_raw} ${_args}")
            else()
                _need("${_bit_op}" "bitrel" "${_mn}" "${_mn_raw} ${_args}")
            endif()
        endforeach()
    elseif(_args STREQUAL "\"\"")
        _need("${_opcode}" "inh" "${_mn}" "${_mn_raw} ${_args}")
    elseif(_args STREQUAL "#*")
        _need("${_opcode}" "imm" "${_mn}" "${_mn_raw} ${_args}")
    elseif(_args STREQUAL ",X")
        _need("${_opcode}" "idx" "${_mn}" "${_mn_raw} ${_args}")
    elseif(_args STREQUAL "*,X")
        if(_mod STREQUAL "MZERO")
            string(SUBSTRING "${_opcode}" 1 1 _op_lo)
            set(_idx8_op "E${_op_lo}")
            _need("${_idx8_op}" "idx8" "${_mn}" "${_mn_raw} zero-page ${_args}")
            _need("${_opcode}" "idx16" "${_mn}" "${_mn_raw} extended ${_args}")
        else()
            _need("${_opcode}" "idx8" "${_mn}" "${_mn_raw} ${_args}")
        endif()
    elseif(_args STREQUAL "*")
        if(_mod STREQUAL "R1")
            _need("${_opcode}" "rel" "${_mn}" "${_mn_raw} ${_args}")
        elseif(_mod STREQUAL "MZERO")
            string(SUBSTRING "${_opcode}" 1 1 _op_lo)
            set(_dir_op "B${_op_lo}")
            _need("${_dir_op}" "dir" "${_mn}" "${_mn_raw} zero-page ${_args}")
            _need("${_opcode}" "ext" "${_mn}" "${_mn_raw} extended ${_args}")
        else()
            if(_bytes STREQUAL "2")
                _need("${_opcode}" "dir" "${_mn}" "${_mn_raw} ${_args}")
            else()
                _need("${_opcode}" "ext" "${_mn}" "${_mn_raw} ${_args}")
            endif()
        endif()
    else()
        message(FATAL_ERROR "unhandled TASM operand form '${_args}' in '${_line}'")
    endif()
endforeach()

if(NOT has_invalid)
    list(APPEND missing "invalid opcode fixture row: opcode $31, mode fcb, mnemonic fcb")
endif()

if(NOT has_trunc_fffe)
    list(APPEND missing "truncated extended fixture row near $1FFE")
endif()

if(NOT has_trunc_ffff)
    list(APPEND missing "truncated immediate fixture row at $1FFF")
endif()

if(missing)
    list(JOIN missing "\n  - " missing_text)
    message(FATAL_ERROR "monitor disassembler coverage audit failed:\n  - ${missing_text}")
endif()
