foreach(_required_var IN ITEMS MONITOR_BINARY MONITOR_SYMBOLS MAME_EXE MAME_STAGE_DIR MONITOR_OUTPUT_DIR)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "${_required_var} is required")
    endif()
endforeach()

set(PROGRAM_START 0x0400)
set(BREAK_ADDR 0x0402)
set(BREAK_AFTER 0x0403)
set(CONT_AFTER 0x0404)
set(FINAL_PC 0x0407)
set(RESULT_ADDR 0x0050)
set(BREAK_OPCODE "A6")
set(PATCH_OPCODE "83")
set(EXPECTED_A "56")
set(EXPECTED_X "34")
set(EXPECTED_SP "7A")
set(STOP_BREAK "05")
set(STOP_SWI "03")

get_filename_component(_monitor_binary "${MONITOR_BINARY}" ABSOLUTE)
get_filename_component(_monitor_symbols "${MONITOR_SYMBOLS}" ABSOLUTE)
get_filename_component(_mame_exe "${MAME_EXE}" ABSOLUTE)
get_filename_component(_monitor_output_dir "${MONITOR_OUTPUT_DIR}" ABSOLUTE)
get_filename_component(_stage_dir "${MAME_STAGE_DIR}" ABSOLUTE BASE_DIR "${_monitor_output_dir}")

foreach(_path_var IN ITEMS _monitor_binary _monitor_symbols _mame_exe)
    if(NOT EXISTS "${${_path_var}}")
        message(FATAL_ERROR "required input does not exist: ${${_path_var}}")
    endif()
endforeach()

file(TO_CMAKE_PATH "${_monitor_output_dir}" _monitor_output_cmp)
file(TO_CMAKE_PATH "${_stage_dir}" _stage_cmp)

if("${_stage_cmp}" STREQUAL "${_monitor_output_cmp}")
    message(FATAL_ERROR "MAME stage directory must not be the monitor output directory")
endif()

string(APPEND _monitor_output_cmp "/")
string(APPEND _stage_cmp "/")
string(FIND "${_stage_cmp}" "${_monitor_output_cmp}" _stage_prefix)
if(NOT _stage_prefix EQUAL 0)
    message(FATAL_ERROR "MAME stage directory must be under the monitor output directory: ${_stage_dir}")
endif()

function(_require_symbol _name)
    if(NOT DEFINED "SYM_${_name}")
        message(FATAL_ERROR "Missing symbol '${_name}' in ${_monitor_symbols}")
    endif()
endfunction()

file(STRINGS "${_monitor_symbols}" _symbol_lines)
foreach(_line IN LISTS _symbol_lines)
    if(_line MATCHES "^([A-Za-z_][A-Za-z0-9_]*)[ \t]+([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])")
        string(TOUPPER "${CMAKE_MATCH_2}" _symbol_value)
        set("SYM_${CMAKE_MATCH_1}" "${_symbol_value}")
    endif()
endforeach()

foreach(_symbol IN ITEMS
        idle
        bp_set
        bp_cont
        bp_hi
        bp_lo
        bp_op
        saved_sp
        saved_pc_hi
        saved_pc_lo
        saved_a
        saved_x
        saved_cc
        stop_rsn
        tmr_vec_hi
        tmr_vec_lo
        tmr_def_hdlr)
    _require_symbol("${_symbol}")
endforeach()

file(REMOVE_RECURSE "${_stage_dir}")
file(MAKE_DIRECTORY
    "${_stage_dir}/roms/m6805sbc"
    "${_stage_dir}/cfg"
)

configure_file("${_monitor_binary}" "${_stage_dir}/roms/m6805sbc/rom1.bin" COPYONLY)
file(WRITE "${_stage_dir}/cfg/m6805sbc.cfg"
    "<?xml version=\"1.0\"?>\r\n"
    "<!-- This file is generated by the monitor MAME test. -->\r\n"
    "<mameconfig version=\"10\">\r\n"
    "    <system name=\"m6805sbc\">\r\n"
    "        <input>\r\n"
    "            <port tag=\":BAUD\" type=\"DIPSWITCH\" mask=\"3\" defvalue=\"0\" value=\"0\" />\r\n"
    "        </input>\r\n"
    "    </system>\r\n"
    "</mameconfig>\r\n"
)

set(_breakpoint_script "${_stage_dir}/breakpoint.lua")
file(WRITE "${_breakpoint_script}"
    "local idle = 0x${SYM_idle}\r\n"
    "local bp_set = 0x${SYM_bp_set}\r\n"
    "local bp_cont = 0x${SYM_bp_cont}\r\n"
    "local bp_hi = 0x${SYM_bp_hi}\r\n"
    "local bp_lo = 0x${SYM_bp_lo}\r\n"
    "local bp_op = 0x${SYM_bp_op}\r\n"
    "local program_start = ${PROGRAM_START}\r\n"
    "local break_addr = ${BREAK_ADDR}\r\n"
    "local result_addr = ${RESULT_ADDR}\r\n"
    "local frames = 0\r\n"
    "local phase = \"wait_reset\"\r\n"
    "local first = {}\r\n"
    "local final = {}\r\n"
    "local cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "local mem = cpu.spaces[\"program\"]\r\n"
    "local function write_word(high_addr, low_addr, value)\r\n"
    "    mem:write_u8(high_addr, math.floor(value / 256))\r\n"
    "    mem:write_u8(low_addr, value % 256)\r\n"
    "end\r\n"
    "local function read_word(high_addr, low_addr)\r\n"
    "    return mem:read_u8(high_addr) * 256 + mem:read_u8(low_addr)\r\n"
    "end\r\n"
    "local function load_program()\r\n"
    "    local program = {0xae, 0x34, 0xa6, 0x56, 0xb7, result_addr, 0x83}\r\n"
    "    for index, byte in ipairs(program) do mem:write_u8(program_start + index - 1, byte) end\r\n"
    "    mem:write_u8(result_addr, 0x00)\r\n"
    "end\r\n"
    "emu.register_frame_done(function()\r\n"
    "    frames = frames + 1\r\n"
    "    cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "    mem = cpu.spaces[\"program\"]\r\n"
    "    if phase == \"wait_reset\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 60 then return end\r\n"
    "        load_program()\r\n"
    "        write_word(bp_hi, bp_lo, break_addr)\r\n"
    "        cpu.state[\"PC\"].value = bp_set\r\n"
    "        phase = \"wait_set\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_set\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 120 then return end\r\n"
    "        first.patched = mem:read_u8(break_addr)\r\n"
    "        first.original = mem:read_u8(bp_op)\r\n"
    "        cpu.state[\"A\"].value = 0x12\r\n"
    "        cpu.state[\"X\"].value = 0x00\r\n"
    "        cpu.state[\"S\"].value = 0x7f\r\n"
    "        cpu.state[\"PC\"].value = program_start\r\n"
    "        phase = \"wait_break\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_break\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 240 then return end\r\n"
    "        first.saved_pc = read_word(0x${SYM_saved_pc_hi}, 0x${SYM_saved_pc_lo})\r\n"
    "        first.saved_a = mem:read_u8(0x${SYM_saved_a})\r\n"
    "        first.saved_x = mem:read_u8(0x${SYM_saved_x})\r\n"
    "        first.saved_sp = mem:read_u8(0x${SYM_saved_sp})\r\n"
    "        first.stop = mem:read_u8(0x${SYM_stop_rsn})\r\n"
    "        first.restored = mem:read_u8(break_addr)\r\n"
    "        cpu.state[\"S\"].value = 0x${EXPECTED_SP}\r\n"
    "        cpu.state[\"PC\"].value = bp_cont\r\n"
    "        phase = \"wait_final_swi\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_final_swi\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 360 then return end\r\n"
    "        final.saved_pc = read_word(0x${SYM_saved_pc_hi}, 0x${SYM_saved_pc_lo})\r\n"
    "        final.saved_a = mem:read_u8(0x${SYM_saved_a})\r\n"
    "        final.saved_x = mem:read_u8(0x${SYM_saved_x})\r\n"
    "        final.saved_sp = mem:read_u8(0x${SYM_saved_sp})\r\n"
    "        final.stop = mem:read_u8(0x${SYM_stop_rsn})\r\n"
    "        final.break_byte = mem:read_u8(break_addr)\r\n"
    "        final.result = mem:read_u8(result_addr)\r\n"
    "        final.timer_vec = read_word(0x${SYM_tmr_vec_hi}, 0x${SYM_tmr_vec_lo})\r\n"
    "        print(string.format(\"BREAKPOINT PATCH=%02X ORIG=%02X FIRST_PC=%04X FIRST_A=%02X FIRST_X=%02X FIRST_SP=%02X FIRST_STOP=%02X RESTORED=%02X FINAL_PC=%04X FINAL_A=%02X FINAL_X=%02X FINAL_SP=%02X FINAL_STOP=%02X FINAL_BP=%02X RESULT=%02X TIMER_VEC=%04X\", first.patched, first.original, first.saved_pc, first.saved_a, first.saved_x, first.saved_sp, first.stop, first.restored, final.saved_pc, final.saved_a, final.saved_x, final.saved_sp, final.stop, final.break_byte, final.result, final.timer_vec))\r\n"
    "        manager.machine:exit()\r\n"
    "        return\r\n"
    "    end\r\n"
    "end, \"breakpoint\")\r\n"
)

execute_process(
    COMMAND
        "${_mame_exe}"
        m6805sbc
        -rompath roms
        -cfg_directory cfg
        -homepath .
        -video none
        -sound none
        -skip_gameinfo
        -nothrottle
        -autoboot_delay 0
        -autoboot_script breakpoint.lua
        -seconds_to_run 5
    WORKING_DIRECTORY "${_stage_dir}"
    RESULT_VARIABLE _mame_result
    OUTPUT_VARIABLE _mame_stdout
    ERROR_VARIABLE _mame_stderr
)

set(_mame_output "${_mame_stdout}\n${_mame_stderr}")

if(NOT _mame_result EQUAL 0)
    message(FATAL_ERROR "MAME failed with exit code ${_mame_result}\n${_mame_output}")
endif()

string(REGEX MATCH "BREAKPOINT " _state_match "${_mame_output}")
if(NOT _state_match)
    message(FATAL_ERROR "MAME output did not report BREAKPOINT\n${_mame_output}")
endif()

function(_capture_hex _out_var _pattern _description)
    string(REGEX MATCH "${_pattern}" _field_match "${_mame_output}")
    if(NOT _field_match)
        message(FATAL_ERROR "MAME output did not report ${_description}\n${_mame_output}")
    endif()

    string(TOUPPER "${CMAKE_MATCH_1}" _captured)
    set(${_out_var} "${_captured}" PARENT_SCOPE)
endfunction()

_capture_hex(_patch "PATCH=([0-9A-Fa-f]+)" "patched breakpoint opcode")
_capture_hex(_orig " ORIG=([0-9A-Fa-f]+)" "original breakpoint opcode")
_capture_hex(_first_pc " FIRST_PC=([0-9A-Fa-f]+)" "breakpoint saved PC")
_capture_hex(_first_a " FIRST_A=([0-9A-Fa-f]+)" "breakpoint saved A")
_capture_hex(_first_x " FIRST_X=([0-9A-Fa-f]+)" "breakpoint saved X")
_capture_hex(_first_sp " FIRST_SP=([0-9A-Fa-f]+)" "breakpoint saved SP")
_capture_hex(_first_stop " FIRST_STOP=([0-9A-Fa-f]+)" "breakpoint stop reason")
_capture_hex(_restored " RESTORED=([0-9A-Fa-f]+)" "restored breakpoint opcode")
_capture_hex(_final_pc " FINAL_PC=([0-9A-Fa-f]+)" "final saved PC")
_capture_hex(_final_a " FINAL_A=([0-9A-Fa-f]+)" "final saved A")
_capture_hex(_final_x " FINAL_X=([0-9A-Fa-f]+)" "final saved X")
_capture_hex(_final_sp " FINAL_SP=([0-9A-Fa-f]+)" "final saved SP")
_capture_hex(_final_stop " FINAL_STOP=([0-9A-Fa-f]+)" "final stop reason")
_capture_hex(_final_bp " FINAL_BP=([0-9A-Fa-f]+)" "final breakpoint opcode")
_capture_hex(_result " RESULT=([0-9A-Fa-f]+)" "program result byte")
_capture_hex(_timer_vec " TIMER_VEC=([0-9A-Fa-f]+)" "restored timer vector")

foreach(_expected_pair IN ITEMS
        "_patch;${PATCH_OPCODE};patched breakpoint opcode"
        "_orig;${BREAK_OPCODE};recorded original opcode"
        "_first_pc;0402;saved PC at breakpoint address"
        "_first_a;12;saved A before breakpoint instruction"
        "_first_x;${EXPECTED_X};saved X before breakpoint instruction"
        "_first_sp;${EXPECTED_SP};saved breakpoint stack pointer"
        "_first_stop;${STOP_BREAK};breakpoint stop reason"
        "_restored;${BREAK_OPCODE};restored opcode after breakpoint hit"
        "_final_pc;0407;final SWI saved PC"
        "_final_a;${EXPECTED_A};final saved A after continue"
        "_final_x;${EXPECTED_X};final saved X after continue"
        "_final_sp;${EXPECTED_SP};final saved SP"
        "_final_stop;${STOP_SWI};final SWI stop reason"
        "_final_bp;${PATCH_OPCODE};re-armed breakpoint opcode"
        "_result;${EXPECTED_A};continued program result"
        "_timer_vec;${SYM_tmr_def_hdlr};restored timer vector")
    string(REPLACE ";" "|" _encoded "${_expected_pair}")
    string(REPLACE "|" ";" _fields "${_encoded}")
    list(GET _fields 0 _var)
    list(GET _fields 1 _expected)
    list(GET _fields 2 _description)
    if(NOT "${${_var}}" STREQUAL "${_expected}")
        message(FATAL_ERROR "Expected ${_description} ${_expected}, got ${${_var}}\n${_mame_output}")
    endif()
endforeach()
