foreach(_required_var IN ITEMS MONITOR_BINARY MONITOR_SYMBOLS MAME_EXE MAME_STAGE_DIR MONITOR_OUTPUT_DIR)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "${_required_var} is required")
    endif()
endforeach()

set(ACIA_CONTROL 0x0006)
set(ACIA_STATUS 0x0006)
set(ACIA_DATA 0x0007)

get_filename_component(_monitor_binary "${MONITOR_BINARY}" ABSOLUTE)
get_filename_component(_monitor_symbols "${MONITOR_SYMBOLS}" ABSOLUTE)
get_filename_component(_mame_exe "${MAME_EXE}" ABSOLUTE)
get_filename_component(_monitor_output_dir "${MONITOR_OUTPUT_DIR}" ABSOLUTE)
get_filename_component(_stage_dir "${MAME_STAGE_DIR}" ABSOLUTE BASE_DIR "${_monitor_output_dir}")

foreach(_path_var IN ITEMS _monitor_binary _monitor_symbols _mame_exe)
    if(NOT EXISTS "${${_path_var}}")
        message(FATAL_ERROR "required input does not exist: ${${_path_var}}")
    endif()
endforeach()

file(TO_CMAKE_PATH "${_monitor_output_dir}" _monitor_output_cmp)
file(TO_CMAKE_PATH "${_stage_dir}" _stage_cmp)

if("${_stage_cmp}" STREQUAL "${_monitor_output_cmp}")
    message(FATAL_ERROR "MAME stage directory must not be the monitor output directory")
endif()

string(APPEND _monitor_output_cmp "/")
string(APPEND _stage_cmp "/")
string(FIND "${_stage_cmp}" "${_monitor_output_cmp}" _stage_prefix)
if(NOT _stage_prefix EQUAL 0)
    message(FATAL_ERROR "MAME stage directory must be under the monitor output directory: ${_stage_dir}")
endif()

function(_require_symbol _name)
    if(NOT DEFINED "SYM_${_name}")
        message(FATAL_ERROR "Missing symbol '${_name}' in ${_monitor_symbols}")
    endif()
endfunction()

file(STRINGS "${_monitor_symbols}" _symbol_lines)
foreach(_line IN LISTS _symbol_lines)
    if(_line MATCHES "^([A-Za-z_][A-Za-z0-9_]*)[ \t]+([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])")
        string(TOUPPER "${CMAKE_MATCH_2}" _symbol_value)
        set("SYM_${CMAKE_MATCH_1}" "${_symbol_value}")
    endif()
endforeach()

foreach(_symbol IN ITEMS
        idle
        asm_key_in
        asm_len
        disasm_pc_hi
        disasm_pc_lo
        saved_sp
        saved_pc_hi
        saved_pc_lo
        saved_a
        saved_x
        saved_cc
        stop_rsn)
    _require_symbol("${_symbol}")
endforeach()

file(REMOVE_RECURSE "${_stage_dir}")
file(MAKE_DIRECTORY
    "${_stage_dir}/roms/m6805sbc"
    "${_stage_dir}/cfg"
)

configure_file("${_monitor_binary}" "${_stage_dir}/roms/m6805sbc/rom1.bin" COPYONLY)
file(WRITE "${_stage_dir}/cfg/m6805sbc.cfg"
    "<?xml version=\"1.0\"?>\r\n"
    "<!-- This file is generated by the monitor MAME test. -->\r\n"
    "<mameconfig version=\"10\">\r\n"
    "    <system name=\"m6805sbc\">\r\n"
    "        <input>\r\n"
    "            <port tag=\":BAUD\" type=\"DIPSWITCH\" mask=\"3\" defvalue=\"0\" value=\"0\" />\r\n"
    "        </input>\r\n"
    "    </system>\r\n"
    "</mameconfig>\r\n"
)

set(_assembler_script "${_stage_dir}/assembler_cmd.lua")
file(WRITE "${_assembler_script}"
    "local idle = 0x${SYM_idle}\r\n"
    "local entry = 0x${SYM_asm_key_in}\r\n"
    "local asm_len = 0x${SYM_asm_len}\r\n"
    "local dpc_hi = 0x${SYM_disasm_pc_hi}\r\n"
    "local dpc_lo = 0x${SYM_disasm_pc_lo}\r\n"
    "local saved = {0x${SYM_saved_sp}, 0x${SYM_saved_pc_hi}, 0x${SYM_saved_pc_lo}, 0x${SYM_saved_a}, 0x${SYM_saved_x}, 0x${SYM_saved_cc}, 0x${SYM_stop_rsn}}\r\n"
    "local keys = {0x6e, 0x6f, 0x70, 0x0d}\r\n"
    "local bytes = {}\r\n"
    "local phase = \"wait_reset\"\r\n"
    "local frames = 0\r\n"
    "local key_frames = 0\r\n"
    "local index = 1\r\n"
    "local cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "local mem = cpu.spaces[\"program\"]\r\n"
    "local function hex_bytes(list)\r\n"
    "    local out = {}\r\n"
    "    for _, byte in ipairs(list) do table.insert(out, string.format(\"%02X\", byte)) end\r\n"
    "    return table.concat(out, \"\")\r\n"
    "end\r\n"
    "local function acia_bytes()\r\n"
    "    return hex_bytes(bytes)\r\n"
    "end\r\n"
    "local function saved_bytes()\r\n"
    "    local out = {}\r\n"
    "    for _, addr in ipairs(saved) do table.insert(out, mem:read_u8(addr)) end\r\n"
    "    return hex_bytes(out)\r\n"
    "end\r\n"
    "local function call_key(value)\r\n"
    "    cpu.state[\"A\"].value = value\r\n"
    "    cpu.state[\"PC\"].value = entry\r\n"
    "end\r\n"
    "mem:install_write_tap(${ACIA_DATA}, ${ACIA_DATA}, \"assembler_cmd_acia_data\", function(offset, data, mask)\r\n"
    "    table.insert(bytes, data & 0xff)\r\n"
    "end)\r\n"
    "mem:install_read_tap(${ACIA_STATUS}, ${ACIA_STATUS}, \"assembler_cmd_acia_status\", function(offset, data, mask)\r\n"
    "    return data | 0x02\r\n"
    "end)\r\n"
    "emu.register_frame_done(function()\r\n"
    "    frames = frames + 1\r\n"
    "    cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "    mem = cpu.spaces[\"program\"]\r\n"
    "    if phase == \"wait_reset\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 60 then return end\r\n"
    "        mem:write_u8(${ACIA_CONTROL}, 0x03)\r\n"
    "        mem:write_u8(${ACIA_CONTROL}, 0x15)\r\n"
    "        mem:write_u8(dpc_hi, 0x04)\r\n"
    "        mem:write_u8(dpc_lo, 0x00)\r\n"
    "        mem:write_u8(0x0400, 0x42)\r\n"
    "        mem:write_u8(0x0401, 0x55)\r\n"
    "        mem:write_u8(saved[1], 0x7d)\r\n"
    "        mem:write_u8(saved[2], 0x12)\r\n"
    "        mem:write_u8(saved[3], 0x34)\r\n"
    "        mem:write_u8(saved[4], 0x56)\r\n"
    "        mem:write_u8(saved[5], 0x78)\r\n"
    "        mem:write_u8(saved[6], 0x09)\r\n"
    "        mem:write_u8(saved[7], 0x02)\r\n"
    "        bytes = {}\r\n"
    "        key_frames = 0\r\n"
    "        call_key(keys[index])\r\n"
    "        phase = \"wait_key\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_key\" then\r\n"
    "        key_frames = key_frames + 1\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and key_frames < 60 then return end\r\n"
    "        index = index + 1\r\n"
    "        if index <= #keys then\r\n"
    "            key_frames = 0\r\n"
    "            call_key(keys[index])\r\n"
    "            return\r\n"
    "        end\r\n"
    "        local pc = mem:read_u8(dpc_hi) * 256 + mem:read_u8(dpc_lo)\r\n"
    "        print(string.format(\"ASM_CMD PC=%04X LEN=%d MEM0=%02X MEM1=%02X COUNT=%d BYTES=%s SAVED=%s\", pc, mem:read_u8(asm_len), mem:read_u8(0x0400), mem:read_u8(0x0401), #bytes, acia_bytes(), saved_bytes()))\r\n"
    "        manager.machine:exit()\r\n"
    "        return\r\n"
    "    end\r\n"
    "end, \"assembler_cmd\")\r\n"
)

execute_process(
    COMMAND
        "${_mame_exe}"
        m6805sbc
        -rompath roms
        -cfg_directory cfg
        -homepath .
        -video none
        -sound none
        -skip_gameinfo
        -nothrottle
        -autoboot_delay 0
        -autoboot_script assembler_cmd.lua
        -seconds_to_run 5
    WORKING_DIRECTORY "${_stage_dir}"
    RESULT_VARIABLE _mame_result
    OUTPUT_VARIABLE _mame_stdout
    ERROR_VARIABLE _mame_stderr
)

set(_mame_output "${_mame_stdout}\n${_mame_stderr}")

if(NOT _mame_result EQUAL 0)
    message(FATAL_ERROR "MAME failed with exit code ${_mame_result}\n${_mame_output}")
endif()

string(REGEX MATCH "ASM_CMD PC=([0-9A-Fa-f]+) LEN=([0-9]+) MEM0=([0-9A-Fa-f][0-9A-Fa-f]) MEM1=([0-9A-Fa-f][0-9A-Fa-f]) COUNT=([0-9]+) BYTES=([0-9A-Fa-f]*) SAVED=([0-9A-Fa-f]+)" _output_match "${_mame_output}")
if(NOT _output_match)
    message(FATAL_ERROR "MAME output did not report ASM_CMD\n${_mame_output}")
endif()

set(_actual_pc "${CMAKE_MATCH_1}")
set(_actual_len "${CMAKE_MATCH_2}")
set(_actual_mem0 "${CMAKE_MATCH_3}")
set(_actual_mem1 "${CMAKE_MATCH_4}")
set(_actual_count "${CMAKE_MATCH_5}")
set(_actual_bytes "${CMAKE_MATCH_6}")
set(_actual_saved "${CMAKE_MATCH_7}")
string(TOUPPER "${_actual_pc}" _actual_pc)
string(TOUPPER "${_actual_mem0}" _actual_mem0)
string(TOUPPER "${_actual_mem1}" _actual_mem1)
string(TOUPPER "${_actual_bytes}" _actual_bytes)
string(TOUPPER "${_actual_saved}" _actual_saved)

if(NOT _actual_pc STREQUAL "0401")
    message(FATAL_ERROR "Expected assembler PC 0401, got ${_actual_pc}\n${_mame_output}")
endif()

if(NOT _actual_len STREQUAL "0")
    message(FATAL_ERROR "Expected assembler line length reset to 0, got ${_actual_len}\n${_mame_output}")
endif()

if(NOT _actual_mem0 STREQUAL "9D" OR NOT _actual_mem1 STREQUAL "55")
    message(FATAL_ERROR "Expected assembled bytes 9D 55, got ${_actual_mem0} ${_actual_mem1}\n${_mame_output}")
endif()

if(NOT _actual_count STREQUAL "4" OR NOT _actual_bytes STREQUAL "6F6B0D0A")
    message(FATAL_ERROR "Expected assembler status bytes 6F6B0D0A, got count=${_actual_count} bytes=${_actual_bytes}\n${_mame_output}")
endif()

if(NOT _actual_saved STREQUAL "7D123456780902")
    message(FATAL_ERROR "Expected saved CPU state untouched, got ${_actual_saved}\n${_mame_output}")
endif()
