if(NOT DEFINED MONITOR_SOURCE)
    message(FATAL_ERROR "MONITOR_SOURCE is required")
endif()

if(NOT EXISTS "${MONITOR_SOURCE}")
    message(FATAL_ERROR "monitor source does not exist: ${MONITOR_SOURCE}")
endif()

file(STRINGS "${MONITOR_SOURCE}" source_lines)

set(active_module "")
set(seen_modules "")
set(errors "")
set(line_no 0)

foreach(line IN LISTS source_lines)
    math(EXPR line_no "${line_no} + 1")

    if(line MATCHES "^[ \t]*\\.module[ \t]+([A-Za-z_][A-Za-z0-9_]*)")
        set(active_module "${CMAKE_MATCH_1}")
        list(APPEND seen_modules "${active_module}")
    endif()

    if(line MATCHES "^([A-Za-z_][A-Za-z0-9_]*):")
        set(label "${CMAKE_MATCH_1}")
        if(active_module STREQUAL "")
            list(APPEND errors "label '${label}' at line ${line_no} appears before any .module")
        endif()
        set("label_module_${label}" "${active_module}")
    endif()

    if(line MATCHES "^[ \t]*\\.org[ \t]+\\$1ff6")
        if(NOT active_module STREQUAL "int_vecs")
            list(APPEND errors ".org $1ff6 at line ${line_no} must be in module 'int_vecs'")
        endif()
    endif()
endforeach()

macro(require_module module)
    list(FIND seen_modules "${module}" module_index)
    if(module_index EQUAL -1)
        list(APPEND errors "missing required module '${module}'")
    endif()
endmacro()

macro(forbid_module module)
    list(FIND seen_modules "${module}" module_index)
    if(NOT module_index EQUAL -1)
        list(APPEND errors "production monitor source must not include test-only module '${module}'")
    endif()
endmacro()

macro(require_label_module label module)
    if(NOT DEFINED label_module_${label})
        list(APPEND errors "missing required label '${label}'")
    elseif(NOT "${label_module_${label}}" STREQUAL "${module}")
        list(APPEND errors "label '${label}' is in module '${label_module_${label}}', expected '${module}'")
    endif()
endmacro()

macro(forbid_label label)
    if(DEFINED label_module_${label})
        list(APPEND errors "production monitor source must not include test-only label '${label}'")
    endif()
endmacro()

require_module("reset")
require_module("int_disp")
require_module("con_io")
require_module("draw_boot")
require_module("draw_cpu")
require_module("scr_out")
require_module("dasm_out")
require_module("hex_out")
require_module("draw_mem_row")
require_module("draw_dasm_row")
require_module("mem_pnl")
require_module("mem_edit")
require_module("mem_cur")
require_module("asm_cmd")
require_module("idle")
require_module("data")

forbid_module("test_hooks")
forbid_label("test_con_out")
forbid_label("test_cpu_out")
forbid_label("test_mem_out")
forbid_label("test_dasm_out")

require_label_module("reset" "reset")
require_label_module("swi" "int_disp")
require_label_module("tmr_disp" "int_disp")
require_label_module("ext_disp" "int_disp")
require_label_module("init_con" "con_io")
require_label_module("chrout" "con_io")
require_label_module("draw_boot" "draw_boot")
require_label_module("draw_cpu" "draw_cpu")
require_label_module("emit_spcs" "scr_out")
require_label_module("dec_inst" "dasm_out")
require_label_module("dasm_line" "dasm_out")
require_label_module("hex_byte" "hex_out")
require_label_module("draw_mem_row" "draw_mem_row")
require_label_module("draw_dasm_row" "draw_dasm_row")
require_label_module("init_mem_pnl" "mem_pnl")
require_label_module("mem_key_in" "mem_edit")
require_label_module("mem_sel_cur" "mem_cur")
require_label_module("mem_cur_lft" "mem_cur")
require_label_module("asm_key_in" "asm_cmd")
require_label_module("idle" "idle")
require_label_module("hex_digits" "data")
require_label_module("boot_txt" "data")

if(errors)
    list(JOIN errors "\n  - " error_text)
    message(FATAL_ERROR "monitor.asm source structure failed:\n  - ${error_text}")
endif()
