foreach(_required_var IN ITEMS MONITOR_BINARY MONITOR_SYMBOLS MAME_EXE MAME_STAGE_DIR MONITOR_OUTPUT_DIR)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "${_required_var} is required")
    endif()
endforeach()

set(ACIA_STATUS 0x0006)
set(ACIA_DATA 0x0007)
set(PROGRAM_START 0x0400)
set(STACK_TOP "7F")
set(EXPECTED_SP "7A")
set(CC_MASKED "08")
set(CC_CLEAR "00")
set(STOP_SWI "03")
set(STOP_STEP "04")

get_filename_component(_monitor_binary "${MONITOR_BINARY}" ABSOLUTE)
get_filename_component(_monitor_symbols "${MONITOR_SYMBOLS}" ABSOLUTE)
get_filename_component(_mame_exe "${MAME_EXE}" ABSOLUTE)
get_filename_component(_monitor_output_dir "${MONITOR_OUTPUT_DIR}" ABSOLUTE)
get_filename_component(_stage_dir "${MAME_STAGE_DIR}" ABSOLUTE BASE_DIR "${_monitor_output_dir}")

foreach(_path_var IN ITEMS _monitor_binary _monitor_symbols _mame_exe)
    if(NOT EXISTS "${${_path_var}}")
        message(FATAL_ERROR "required input does not exist: ${${_path_var}}")
    endif()
endforeach()

file(TO_CMAKE_PATH "${_monitor_output_dir}" _monitor_output_cmp)
file(TO_CMAKE_PATH "${_stage_dir}" _stage_cmp)

if("${_stage_cmp}" STREQUAL "${_monitor_output_cmp}")
    message(FATAL_ERROR "MAME stage directory must not be the monitor output directory")
endif()

string(APPEND _monitor_output_cmp "/")
string(APPEND _stage_cmp "/")
string(FIND "${_stage_cmp}" "${_monitor_output_cmp}" _stage_prefix)
if(NOT _stage_prefix EQUAL 0)
    message(FATAL_ERROR "MAME stage directory must be under the monitor output directory: ${_stage_dir}")
endif()

function(_require_symbol _name)
    if(NOT DEFINED "SYM_${_name}")
        message(FATAL_ERROR "Missing symbol '${_name}' in ${_monitor_symbols}")
    endif()
endfunction()

file(STRINGS "${_monitor_symbols}" _symbol_lines)
foreach(_line IN LISTS _symbol_lines)
    if(_line MATCHES "^([A-Za-z_][A-Za-z0-9_]*)[ \t]+([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])")
        string(TOUPPER "${CMAKE_MATCH_2}" _symbol_value)
        set("SYM_${CMAKE_MATCH_1}" "${_symbol_value}")
    endif()
endforeach()

foreach(_symbol IN ITEMS
        monitor_idle
        go_cmd
        stp_cmd
        trc_cmd
        saved_sp
        saved_pc_hi
        saved_pc_lo
        saved_a
        saved_x
        saved_cc
        stop_rsn
        disasm_pc_hi
        disasm_pc_lo
        tmr_vec_hi
        tmr_vec_lo
        tmr_def_hdlr)
    _require_symbol("${_symbol}")
endforeach()

file(REMOVE_RECURSE "${_stage_dir}")
file(MAKE_DIRECTORY
    "${_stage_dir}/roms/m6805sbc"
    "${_stage_dir}/cfg"
)

configure_file("${_monitor_binary}" "${_stage_dir}/roms/m6805sbc/rom1.bin" COPYONLY)
file(WRITE "${_stage_dir}/cfg/m6805sbc.cfg"
    "<?xml version=\"1.0\"?>\r\n"
    "<!-- This file is generated by the monitor MAME test. -->\r\n"
    "<mameconfig version=\"10\">\r\n"
    "    <system name=\"m6805sbc\">\r\n"
    "        <input>\r\n"
    "            <port tag=\":BAUD\" type=\"DIPSWITCH\" mask=\"3\" defvalue=\"0\" value=\"0\" />\r\n"
    "        </input>\r\n"
    "    </system>\r\n"
    "</mameconfig>\r\n"
)

set(_exec_cmds_script "${_stage_dir}/exec_cmds.lua")
file(WRITE "${_exec_cmds_script}"
    "local monitor_idle = 0x${SYM_monitor_idle}\r\n"
    "local go_cmd = 0x${SYM_go_cmd}\r\n"
    "local stp_cmd = 0x${SYM_stp_cmd}\r\n"
    "local trc_cmd = 0x${SYM_trc_cmd}\r\n"
    "local program_start = ${PROGRAM_START}\r\n"
    "local frames = 0\r\n"
    "local phase = \"wait_reset\"\r\n"
    "local results = {}\r\n"
    "local cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "local mem = cpu.spaces[\"program\"]\r\n"
    "mem:install_write_tap(${ACIA_DATA}, ${ACIA_DATA}, \"exec_cmds_acia_data\", function(offset, data, mask)\r\n"
    "end)\r\n"
    "mem:install_read_tap(${ACIA_STATUS}, ${ACIA_STATUS}, \"exec_cmds_acia_status\", function(offset, data, mask)\r\n"
    "    return data | 0x02\r\n"
    "end)\r\n"
    "local function write_word(high_addr, low_addr, value)\r\n"
    "    mem:write_u8(high_addr, math.floor(value / 256))\r\n"
    "    mem:write_u8(low_addr, value % 256)\r\n"
    "end\r\n"
    "local function read_word(high_addr, low_addr)\r\n"
    "    return mem:read_u8(high_addr) * 256 + mem:read_u8(low_addr)\r\n"
    "end\r\n"
    "local function load_program(bytes)\r\n"
    "    for index, byte in ipairs(bytes) do mem:write_u8(program_start + index - 1, byte) end\r\n"
    "end\r\n"
    "local function seed_saved(pc, a, x, cc)\r\n"
    "    mem:write_u8(0x${SYM_saved_sp}, 0x${EXPECTED_SP})\r\n"
    "    write_word(0x${SYM_saved_pc_hi}, 0x${SYM_saved_pc_lo}, pc)\r\n"
    "    mem:write_u8(0x${SYM_saved_a}, a)\r\n"
    "    mem:write_u8(0x${SYM_saved_x}, x)\r\n"
    "    mem:write_u8(0x${SYM_saved_cc}, cc)\r\n"
    "    cpu.state[\"S\"].value = 0x${STACK_TOP}\r\n"
    "end\r\n"
    "local function capture(prefix)\r\n"
    "    results[prefix .. \"_pc\"] = read_word(0x${SYM_saved_pc_hi}, 0x${SYM_saved_pc_lo})\r\n"
    "    results[prefix .. \"_a\"] = mem:read_u8(0x${SYM_saved_a})\r\n"
    "    results[prefix .. \"_x\"] = mem:read_u8(0x${SYM_saved_x})\r\n"
    "    results[prefix .. \"_cc\"] = mem:read_u8(0x${SYM_saved_cc})\r\n"
    "    results[prefix .. \"_sp\"] = mem:read_u8(0x${SYM_saved_sp})\r\n"
    "    results[prefix .. \"_stop\"] = mem:read_u8(0x${SYM_stop_rsn})\r\n"
    "    results[prefix .. \"_dasm\"] = read_word(0x${SYM_disasm_pc_hi}, 0x${SYM_disasm_pc_lo})\r\n"
    "end\r\n"
    "emu.register_frame_done(function()\r\n"
    "    frames = frames + 1\r\n"
    "    cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "    mem = cpu.spaces[\"program\"]\r\n"
    "    if phase == \"wait_reset\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= monitor_idle and frames < 60 then return end\r\n"
    "        load_program({0xae, 0x34, 0xa6, 0x56, 0x83})\r\n"
    "        seed_saved(program_start, 0x12, 0x00, 0x${CC_MASKED})\r\n"
    "        cpu.state[\"PC\"].value = go_cmd\r\n"
    "        phase = \"wait_go\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_go\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= monitor_idle and frames < 240 then return end\r\n"
    "        capture(\"go\")\r\n"
    "        load_program({0xa6, 0x22, 0x9d, 0x83})\r\n"
    "        seed_saved(program_start, 0x11, 0x44, 0x${CC_MASKED})\r\n"
    "        write_word(0x${SYM_disasm_pc_hi}, 0x${SYM_disasm_pc_lo}, 0x2222)\r\n"
    "        cpu.state[\"PC\"].value = stp_cmd\r\n"
    "        phase = \"wait_step\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_step\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= monitor_idle and frames < 420 then return end\r\n"
    "        capture(\"step\")\r\n"
    "        load_program({0xa6, 0x11, 0xa6, 0x12, 0xa6, 0x13, 0x83})\r\n"
    "        seed_saved(program_start, 0x10, 0x55, 0x${CC_CLEAR})\r\n"
    "        write_word(0x${SYM_disasm_pc_hi}, 0x${SYM_disasm_pc_lo}, 0x3333)\r\n"
    "        cpu.state[\"PC\"].value = trc_cmd\r\n"
    "        phase = \"wait_trace\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_trace\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= monitor_idle and frames < 720 then return end\r\n"
    "        capture(\"trace\")\r\n"
    "        results[\"timer_vec\"] = read_word(0x${SYM_tmr_vec_hi}, 0x${SYM_tmr_vec_lo})\r\n"
    "        print(string.format(\"EXEC_CMDS GO_PC=%04X GO_A=%02X GO_X=%02X GO_CC=%02X GO_SP=%02X GO_STOP=%02X STEP_PC=%04X STEP_A=%02X STEP_X=%02X STEP_CC=%02X STEP_SP=%02X STEP_STOP=%02X STEP_DASM=%04X TRACE_PC=%04X TRACE_A=%02X TRACE_X=%02X TRACE_CC=%02X TRACE_SP=%02X TRACE_STOP=%02X TRACE_DASM=%04X TIMER_VEC=%04X\", results.go_pc, results.go_a, results.go_x, results.go_cc, results.go_sp, results.go_stop, results.step_pc, results.step_a, results.step_x, results.step_cc, results.step_sp, results.step_stop, results.step_dasm, results.trace_pc, results.trace_a, results.trace_x, results.trace_cc, results.trace_sp, results.trace_stop, results.trace_dasm, results.timer_vec))\r\n"
    "        manager.machine:exit()\r\n"
    "        return\r\n"
    "    end\r\n"
    "end, \"exec_cmds\")\r\n"
)

execute_process(
    COMMAND
        "${_mame_exe}"
        m6805sbc
        -rompath roms
        -cfg_directory cfg
        -homepath .
        -video none
        -sound none
        -skip_gameinfo
        -nothrottle
        -autoboot_delay 0
        -autoboot_script exec_cmds.lua
        -seconds_to_run 7
    WORKING_DIRECTORY "${_stage_dir}"
    RESULT_VARIABLE _mame_result
    OUTPUT_VARIABLE _mame_stdout
    ERROR_VARIABLE _mame_stderr
)

set(_mame_output "${_mame_stdout}\n${_mame_stderr}")

if(NOT _mame_result EQUAL 0)
    message(FATAL_ERROR "MAME failed with exit code ${_mame_result}\n${_mame_output}")
endif()

string(REGEX MATCH "EXEC_CMDS " _state_match "${_mame_output}")
if(NOT _state_match)
    message(FATAL_ERROR "MAME output did not report EXEC_CMDS\n${_mame_output}")
endif()

function(_capture_hex _out_var _pattern _description)
    string(REGEX MATCH "${_pattern}" _field_match "${_mame_output}")
    if(NOT _field_match)
        message(FATAL_ERROR "MAME output did not report ${_description}\n${_mame_output}")
    endif()

    string(TOUPPER "${CMAKE_MATCH_1}" _captured)
    set(${_out_var} "${_captured}" PARENT_SCOPE)
endfunction()

_capture_hex(_go_pc "GO_PC=([0-9A-Fa-f]+)" "GO saved PC")
_capture_hex(_go_a " GO_A=([0-9A-Fa-f]+)" "GO saved A")
_capture_hex(_go_x " GO_X=([0-9A-Fa-f]+)" "GO saved X")
_capture_hex(_go_cc " GO_CC=([0-9A-Fa-f]+)" "GO saved CC")
_capture_hex(_go_sp " GO_SP=([0-9A-Fa-f]+)" "GO saved SP")
_capture_hex(_go_stop " GO_STOP=([0-9A-Fa-f]+)" "GO stop reason")
_capture_hex(_step_pc " STEP_PC=([0-9A-Fa-f]+)" "STEP saved PC")
_capture_hex(_step_a " STEP_A=([0-9A-Fa-f]+)" "STEP saved A")
_capture_hex(_step_x " STEP_X=([0-9A-Fa-f]+)" "STEP saved X")
_capture_hex(_step_cc " STEP_CC=([0-9A-Fa-f]+)" "STEP saved CC")
_capture_hex(_step_sp " STEP_SP=([0-9A-Fa-f]+)" "STEP saved SP")
_capture_hex(_step_stop " STEP_STOP=([0-9A-Fa-f]+)" "STEP stop reason")
_capture_hex(_step_dasm " STEP_DASM=([0-9A-Fa-f]+)" "STEP disassembly PC")
_capture_hex(_trace_pc " TRACE_PC=([0-9A-Fa-f]+)" "TRACE saved PC")
_capture_hex(_trace_a " TRACE_A=([0-9A-Fa-f]+)" "TRACE saved A")
_capture_hex(_trace_x " TRACE_X=([0-9A-Fa-f]+)" "TRACE saved X")
_capture_hex(_trace_cc " TRACE_CC=([0-9A-Fa-f]+)" "TRACE saved CC")
_capture_hex(_trace_sp " TRACE_SP=([0-9A-Fa-f]+)" "TRACE saved SP")
_capture_hex(_trace_stop " TRACE_STOP=([0-9A-Fa-f]+)" "TRACE stop reason")
_capture_hex(_trace_dasm " TRACE_DASM=([0-9A-Fa-f]+)" "TRACE disassembly PC")
_capture_hex(_timer_vec " TIMER_VEC=([0-9A-Fa-f]+)" "timer vector")

foreach(_expected_pair IN ITEMS
        "_go_pc;0405;GO saved PC after SWI"
        "_go_a;56;GO saved A"
        "_go_x;34;GO saved X"
        "_go_cc;${CC_MASKED};GO saved condition codes"
        "_go_sp;${EXPECTED_SP};GO saved stack pointer"
        "_go_stop;${STOP_SWI};GO stop reason"
        "_step_pc;0402;STEP saved PC after one instruction"
        "_step_a;22;STEP saved A"
        "_step_x;44;STEP saved X"
        "_step_cc;${CC_MASKED};STEP saved condition codes"
        "_step_sp;${EXPECTED_SP};STEP saved stack pointer"
        "_step_stop;${STOP_STEP};STEP stop reason"
        "_step_dasm;0403;STEP disassembly panel PC"
        "_trace_pc;0406;TRACE saved PC after three instructions"
        "_trace_a;13;TRACE saved A"
        "_trace_x;55;TRACE saved X"
        "_trace_cc;${CC_CLEAR};TRACE saved condition codes"
        "_trace_sp;${EXPECTED_SP};TRACE saved stack pointer"
        "_trace_stop;${STOP_STEP};TRACE stop reason"
        "_trace_dasm;0407;TRACE disassembly panel PC"
        "_timer_vec;${SYM_tmr_def_hdlr};restored timer RAM vector")
    string(REPLACE ";" "|" _encoded "${_expected_pair}")
    string(REPLACE "|" ";" _fields "${_encoded}")
    list(GET _fields 0 _var)
    list(GET _fields 1 _expected)
    list(GET _fields 2 _description)
    if(NOT "${${_var}}" STREQUAL "${_expected}")
        message(FATAL_ERROR "Expected ${_description} ${_expected}, got ${${_var}}\n${_mame_output}")
    endif()
endforeach()
