foreach(_required_var IN ITEMS MONITOR_BINARY MONITOR_SYMBOLS SREC_TEST_BINARY MAME_EXE MAME_STAGE_DIR MONITOR_OUTPUT_DIR)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "${_required_var} is required")
    endif()
endforeach()

set(ACIA_STATUS 0x0006)
set(ACIA_CONTROL 0x0006)
set(ACIA_DATA 0x0007)
set(PROGRAM_START 0x0200)
set(SREC_ADDR 0x0110)
set(TEST_MODE 0x00FF)
set(TEST_DONE 0x00FE)
set(VALID_RECORD "S107011001020304DD\\r\\nS9030000FC\\r\\n")
set(INVALID_RECORD "S107011001020304DC\\r\\n")
set(VALID_OUT "6F6B0D0A")
set(INVALID_OUT "6572720D0A")
set(DUMP_OUT "5331303730313130303130323033303444440D0A533930333030303046430D0A")

get_filename_component(_monitor_binary "${MONITOR_BINARY}" ABSOLUTE)
get_filename_component(_monitor_symbols "${MONITOR_SYMBOLS}" ABSOLUTE)
get_filename_component(_srec_test_binary "${SREC_TEST_BINARY}" ABSOLUTE)
get_filename_component(_mame_exe "${MAME_EXE}" ABSOLUTE)
get_filename_component(_monitor_output_dir "${MONITOR_OUTPUT_DIR}" ABSOLUTE)
get_filename_component(_stage_dir "${MAME_STAGE_DIR}" ABSOLUTE BASE_DIR "${_monitor_output_dir}")

foreach(_path_var IN ITEMS _monitor_binary _monitor_symbols _srec_test_binary _mame_exe)
    if(NOT EXISTS "${${_path_var}}")
        message(FATAL_ERROR "required input does not exist: ${${_path_var}}")
    endif()
endforeach()

file(TO_CMAKE_PATH "${_monitor_output_dir}" _monitor_output_cmp)
file(TO_CMAKE_PATH "${_stage_dir}" _stage_cmp)

if("${_stage_cmp}" STREQUAL "${_monitor_output_cmp}")
    message(FATAL_ERROR "MAME stage directory must not be the monitor output directory")
endif()

string(APPEND _monitor_output_cmp "/")
string(APPEND _stage_cmp "/")
string(FIND "${_stage_cmp}" "${_monitor_output_cmp}" _stage_prefix)
if(NOT _stage_prefix EQUAL 0)
    message(FATAL_ERROR "MAME stage directory must be under the monitor output directory: ${_stage_dir}")
endif()

function(_require_symbol _name)
    if(NOT DEFINED "SYM_${_name}")
        message(FATAL_ERROR "Missing symbol '${_name}' in ${_monitor_symbols}")
    endif()
endfunction()

function(_binary_as_lua _out_var _path)
    file(READ "${_path}" _bytes_hex HEX)
    string(REGEX REPLACE "([0-9A-Fa-f][0-9A-Fa-f])" "0x\\1;" _byte_list "${_bytes_hex}")
    string(REGEX REPLACE ";$" "" _byte_list "${_byte_list}")
    string(REPLACE ";" ", " _lua_bytes "${_byte_list}")
    set(${_out_var} "${_lua_bytes}" PARENT_SCOPE)
endfunction()

file(STRINGS "${_monitor_symbols}" _symbol_lines)
foreach(_line IN LISTS _symbol_lines)
    if(_line MATCHES "^([A-Za-z_][A-Za-z0-9_]*)[ \t]+([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])")
        string(TOUPPER "${CMAKE_MATCH_2}" _symbol_value)
        set("SYM_${CMAKE_MATCH_1}" "${_symbol_value}")
    endif()
endforeach()

_require_symbol("idle")
_require_symbol("srec_load")
_require_symbol("srec_dump")

_binary_as_lua(_srec_program "${_srec_test_binary}")

file(REMOVE_RECURSE "${_stage_dir}")
file(MAKE_DIRECTORY
    "${_stage_dir}/roms/m6805sbc"
    "${_stage_dir}/cfg"
)

configure_file("${_monitor_binary}" "${_stage_dir}/roms/m6805sbc/rom1.bin" COPYONLY)
file(WRITE "${_stage_dir}/cfg/m6805sbc.cfg"
    "<?xml version=\"1.0\"?>\r\n"
    "<!-- This file is generated by the monitor MAME test. -->\r\n"
    "<mameconfig version=\"10\">\r\n"
    "    <system name=\"m6805sbc\">\r\n"
    "        <input>\r\n"
    "            <port tag=\":BAUD\" type=\"DIPSWITCH\" mask=\"3\" defvalue=\"0\" value=\"0\" />\r\n"
    "        </input>\r\n"
    "    </system>\r\n"
    "</mameconfig>\r\n"
)

set(_srec_script "${_stage_dir}/srec_transfer.lua")
file(WRITE "${_srec_script}"
    "local idle = 0x${SYM_idle}\r\n"
    "local program_start = ${PROGRAM_START}\r\n"
    "local srec_addr = ${SREC_ADDR}\r\n"
    "local mode_addr = ${TEST_MODE}\r\n"
    "local done_addr = ${TEST_DONE}\r\n"
    "local program = { ${_srec_program} }\r\n"
    "local valid_record = \"${VALID_RECORD}\"\r\n"
    "local invalid_record = \"${INVALID_RECORD}\"\r\n"
    "local input = {}\r\n"
    "local input_pos = 1\r\n"
    "local output = {}\r\n"
    "local result = {}\r\n"
    "local phase = \"wait_reset\"\r\n"
    "local frames = 0\r\n"
    "local cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "local mem = cpu.spaces[\"program\"]\r\n"
    "local function hex_bytes(bytes)\r\n"
    "    local out = {}\r\n"
    "    for _, byte in ipairs(bytes) do table.insert(out, string.format(\"%02X\", byte)) end\r\n"
    "    return table.concat(out, \"\")\r\n"
    "end\r\n"
    "local function read_mem_hex(address, count)\r\n"
    "    local out = {}\r\n"
    "    for offset = 0, count - 1 do table.insert(out, mem:read_u8(address + offset)) end\r\n"
    "    return hex_bytes(out)\r\n"
    "end\r\n"
    "local function seed_mem(a, b, c, d)\r\n"
    "    mem:write_u8(srec_addr + 0, a)\r\n"
    "    mem:write_u8(srec_addr + 1, b)\r\n"
    "    mem:write_u8(srec_addr + 2, c)\r\n"
    "    mem:write_u8(srec_addr + 3, d)\r\n"
    "end\r\n"
    "local function set_input(text)\r\n"
    "    input = {}\r\n"
    "    for index = 1, #text do table.insert(input, text:byte(index)) end\r\n"
    "    input_pos = 1\r\n"
    "    output = {}\r\n"
    "end\r\n"
    "local function start_program(mode, text)\r\n"
    "    set_input(text)\r\n"
    "    mem:write_u8(done_addr, 0)\r\n"
    "    mem:write_u8(mode_addr, mode)\r\n"
    "    cpu.state[\"S\"].value = 0x7f\r\n"
    "    cpu.state[\"PC\"].value = program_start\r\n"
    "end\r\n"
    "mem:install_write_tap(${ACIA_DATA}, ${ACIA_DATA}, \"srec_acia_data\", function(offset, data, mask)\r\n"
    "    table.insert(output, data & 0xff)\r\n"
    "end)\r\n"
    "mem:install_read_tap(${ACIA_STATUS}, ${ACIA_STATUS}, \"srec_acia_status\", function(offset, data, mask)\r\n"
    "    local ready = input_pos <= #input and 0x01 or 0x00\r\n"
    "    return data | 0x02 | ready\r\n"
    "end)\r\n"
    "mem:install_read_tap(${ACIA_DATA}, ${ACIA_DATA}, \"srec_acia_read\", function(offset, data, mask)\r\n"
    "    local byte = input[input_pos] or 0\r\n"
    "    input_pos = input_pos + 1\r\n"
    "    return byte\r\n"
    "end)\r\n"
    "emu.register_frame_done(function()\r\n"
    "    frames = frames + 1\r\n"
    "    cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "    mem = cpu.spaces[\"program\"]\r\n"
    "    if phase == \"wait_reset\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 60 then return end\r\n"
    "        mem:write_u8(${ACIA_CONTROL}, 0x03)\r\n"
    "        mem:write_u8(${ACIA_CONTROL}, 0x15)\r\n"
    "        for index, byte in ipairs(program) do mem:write_u8(program_start + index - 1, byte) end\r\n"
    "        seed_mem(0x00, 0x00, 0x00, 0x00)\r\n"
    "        start_program(0, valid_record)\r\n"
    "        phase = \"wait_valid\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_valid\" then\r\n"
    "        if mem:read_u8(done_addr) == 0 and frames < 600 then return end\r\n"
    "        result.valid_mem = read_mem_hex(srec_addr, 4)\r\n"
    "        result.valid_out = hex_bytes(output)\r\n"
    "        seed_mem(0xa5, 0x5a, 0xc3, 0x3c)\r\n"
    "        start_program(0, invalid_record)\r\n"
    "        phase = \"wait_invalid\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_invalid\" then\r\n"
    "        if mem:read_u8(done_addr) == 0 and frames < 1200 then return end\r\n"
    "        result.invalid_mem = read_mem_hex(srec_addr, 4)\r\n"
    "        result.invalid_out = hex_bytes(output)\r\n"
    "        seed_mem(0x01, 0x02, 0x03, 0x04)\r\n"
    "        start_program(1, \"\")\r\n"
    "        phase = \"wait_dump\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_dump\" then\r\n"
    "        if mem:read_u8(done_addr) == 0 and frames < 1800 then return end\r\n"
    "        result.dump_out = hex_bytes(output)\r\n"
    "        print(string.format(\"SREC_TRANSFER VALID_MEM=%s VALID_OUT=%s INVALID_MEM=%s INVALID_OUT=%s DUMP_OUT=%s\", result.valid_mem, result.valid_out, result.invalid_mem, result.invalid_out, result.dump_out))\r\n"
    "        manager.machine:exit()\r\n"
    "        return\r\n"
    "    end\r\n"
    "end, \"srec_transfer\")\r\n"
)

execute_process(
    COMMAND
        "${_mame_exe}"
        m6805sbc
        -rompath roms
        -cfg_directory cfg
        -homepath .
        -video none
        -sound none
        -skip_gameinfo
        -nothrottle
        -autoboot_delay 0
        -autoboot_script srec_transfer.lua
        -seconds_to_run 8
    WORKING_DIRECTORY "${_stage_dir}"
    RESULT_VARIABLE _mame_result
    OUTPUT_VARIABLE _mame_stdout
    ERROR_VARIABLE _mame_stderr
)

set(_mame_output "${_mame_stdout}\n${_mame_stderr}")

if(NOT _mame_result EQUAL 0)
    message(FATAL_ERROR "MAME failed with exit code ${_mame_result}\n${_mame_output}")
endif()

string(REGEX MATCH "SREC_TRANSFER " _state_match "${_mame_output}")
if(NOT _state_match)
    message(FATAL_ERROR "MAME output did not report SREC_TRANSFER\n${_mame_output}")
endif()

function(_capture_hex _out_var _pattern _description)
    string(REGEX MATCH "${_pattern}" _field_match "${_mame_output}")
    if(NOT _field_match)
        message(FATAL_ERROR "MAME output did not report ${_description}\n${_mame_output}")
    endif()

    string(TOUPPER "${CMAKE_MATCH_1}" _captured)
    set(${_out_var} "${_captured}" PARENT_SCOPE)
endfunction()

_capture_hex(_valid_mem "VALID_MEM=([0-9A-Fa-f]+)" "valid load memory")
_capture_hex(_valid_out " VALID_OUT=([0-9A-Fa-f]*)" "valid load status")
_capture_hex(_invalid_mem " INVALID_MEM=([0-9A-Fa-f]+)" "invalid load memory")
_capture_hex(_invalid_out " INVALID_OUT=([0-9A-Fa-f]*)" "invalid load status")
_capture_hex(_dump_out " DUMP_OUT=([0-9A-Fa-f]*)" "dump output")

foreach(_expected_pair IN ITEMS
        "_valid_mem;01020304;valid loaded bytes"
        "_valid_out;${VALID_OUT};valid load status"
        "_invalid_mem;A55AC33C;invalid load unchanged bytes"
        "_invalid_out;${INVALID_OUT};invalid load status"
        "_dump_out;${DUMP_OUT};dump S-record bytes")
    string(REPLACE ";" "|" _encoded "${_expected_pair}")
    string(REPLACE "|" ";" _fields "${_encoded}")
    list(GET _fields 0 _var)
    list(GET _fields 1 _expected)
    list(GET _fields 2 _description)
    if(NOT "${${_var}}" STREQUAL "${_expected}")
        message(FATAL_ERROR "Expected ${_description} ${_expected}, got ${${_var}}\n${_mame_output}")
    endif()
endforeach()
