foreach(required_var IN ITEMS MONITOR_SOURCE)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()

if(NOT EXISTS "${MONITOR_SOURCE}")
    message(FATAL_ERROR "monitor source does not exist: ${MONITOR_SOURCE}")
endif()

set(errors "")

file(STRINGS "${MONITOR_SOURCE}" source_lines)

set(section "")
set(cpu_text_uses_msg_end FALSE)
set(cpu_text_has_nul FALSE)
set(boot_has_old_clear FALSE)
set(boot_has_old_position FALSE)
set(boot_has_default_erase FALSE)
set(boot_has_horizontal_position FALSE)

foreach(line IN LISTS source_lines)
    if(line MATCHES "^cpu_txt:")
        set(section "cpu")
    elseif(line MATCHES "^op_adc_imm")
        set(section "")
    elseif(line MATCHES "^boot_txt:")
        set(section "boot")
    elseif(line MATCHES "^rom_end:")
        set(section "")
    endif()

    if(section STREQUAL "cpu")
        if(line MATCHES "\\.byte.*NUL")
            set(cpu_text_has_nul TRUE)
        endif()
        if(line MATCHES "msg_end")
            set(cpu_text_uses_msg_end TRUE)
        endif()
    elseif(section STREQUAL "boot")
        if(line MATCHES "\\.(text|byte)[ \t]+.*\"\\[2J\"")
            set(boot_has_old_clear TRUE)
        endif()
        if(line MATCHES "\\.(text|byte)[ \t]+.*\"\\[1;68H\"")
            set(boot_has_old_position TRUE)
        endif()
        if(line MATCHES "\\.(text|byte)[ \t]+.*\"\\[J\"")
            set(boot_has_default_erase TRUE)
        endif()
        if(line MATCHES "\\.(text|byte)[ \t]+.*\"\\[68G\"")
            set(boot_has_horizontal_position TRUE)
        endif()
    endif()
endforeach()

if(cpu_text_has_nul)
    list(APPEND errors "CPU/status text fragments should use high-bit terminators, not NUL bytes")
endif()

if(NOT cpu_text_uses_msg_end)
    list(APPEND errors "CPU/status text fragments should mark final bytes with msg_end")
endif()

if(boot_has_old_clear)
    list(APPEND errors "boot clear sequence should use ESC[J default erase instead of ESC[2J")
endif()

if(boot_has_old_position)
    list(APPEND errors "boot version positioning should use horizontal position ESC[68G after HOME")
endif()

if(NOT boot_has_default_erase)
    list(APPEND errors "boot text should include ESC[J default erase")
endif()

if(NOT boot_has_horizontal_position)
    list(APPEND errors "boot text should include ESC[68G horizontal position")
endif()

if(errors)
    string(REPLACE ";" "\n  - " error_text "${errors}")
    message(FATAL_ERROR "monitor table encoding failed:\n  - ${error_text}")
endif()
