foreach(_required_var IN ITEMS MONITOR_BINARY MONITOR_SYMBOLS CPU_ROW_EXPECTED MAME_EXE MAME_STAGE_DIR MONITOR_OUTPUT_DIR)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "${_required_var} is required")
    endif()
endforeach()

set(ACIA_CONTROL 0x0006)
set(ACIA_DATA 0x0007)

get_filename_component(_monitor_binary "${MONITOR_BINARY}" ABSOLUTE)
get_filename_component(_monitor_symbols "${MONITOR_SYMBOLS}" ABSOLUTE)
get_filename_component(_cpu_row_expected "${CPU_ROW_EXPECTED}" ABSOLUTE)
get_filename_component(_mame_exe "${MAME_EXE}" ABSOLUTE)
get_filename_component(_monitor_output_dir "${MONITOR_OUTPUT_DIR}" ABSOLUTE)
get_filename_component(_stage_dir "${MAME_STAGE_DIR}" ABSOLUTE BASE_DIR "${_monitor_output_dir}")

if(NOT EXISTS "${_monitor_binary}")
    message(FATAL_ERROR "Monitor binary does not exist: ${_monitor_binary}")
endif()

if(NOT EXISTS "${_monitor_symbols}")
    message(FATAL_ERROR "Monitor symbols do not exist: ${_monitor_symbols}")
endif()

if(NOT EXISTS "${_cpu_row_expected}")
    message(FATAL_ERROR "Expected CPU row fixture does not exist: ${_cpu_row_expected}")
endif()

if(NOT EXISTS "${_mame_exe}")
    message(FATAL_ERROR "MAME executable does not exist: ${_mame_exe}")
endif()

file(TO_CMAKE_PATH "${_monitor_output_dir}" _monitor_output_cmp)
file(TO_CMAKE_PATH "${_stage_dir}" _stage_cmp)

if("${_stage_cmp}" STREQUAL "${_monitor_output_cmp}")
    message(FATAL_ERROR "MAME stage directory must not be the monitor output directory")
endif()

string(APPEND _monitor_output_cmp "/")
string(APPEND _stage_cmp "/")
string(FIND "${_stage_cmp}" "${_monitor_output_cmp}" _stage_prefix)
if(NOT _stage_prefix EQUAL 0)
    message(FATAL_ERROR "MAME stage directory must be under the monitor output directory: ${_stage_dir}")
endif()

function(_require_symbol _name)
    if(NOT DEFINED "SYM_${_name}")
        message(FATAL_ERROR "Missing symbol '${_name}' in ${_monitor_symbols}")
    endif()
endfunction()

file(STRINGS "${_monitor_symbols}" _symbol_lines)
foreach(_line IN LISTS _symbol_lines)
    if(_line MATCHES "^([A-Za-z_][A-Za-z0-9_]*)[ \t]+([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])")
        string(TOUPPER "${CMAKE_MATCH_2}" _symbol_value)
        set("SYM_${CMAKE_MATCH_1}" "${_symbol_value}")
    endif()
endforeach()

_require_symbol("monitor_idle")
_require_symbol("test_cpu_row_output")

file(READ "${_cpu_row_expected}" _expected_bytes HEX)
string(TOUPPER "${_expected_bytes}" _expected_bytes)
string(LENGTH "${_expected_bytes}" _expected_hex_length)
math(EXPR _expected_count "${_expected_hex_length} / 2")

file(REMOVE_RECURSE "${_stage_dir}")
file(MAKE_DIRECTORY
    "${_stage_dir}/roms/m6805sbc"
    "${_stage_dir}/cfg"
)

configure_file("${_monitor_binary}" "${_stage_dir}/roms/m6805sbc/rom1.bin" COPYONLY)
file(WRITE "${_stage_dir}/cfg/m6805sbc.cfg"
    "<?xml version=\"1.0\"?>\r\n"
    "<!-- This file is generated by the monitor MAME test. -->\r\n"
    "<mameconfig version=\"10\">\r\n"
    "    <system name=\"m6805sbc\">\r\n"
    "        <input>\r\n"
    "            <port tag=\":BAUD\" type=\"DIPSWITCH\" mask=\"3\" defvalue=\"0\" value=\"0\" />\r\n"
    "        </input>\r\n"
    "    </system>\r\n"
    "</mameconfig>\r\n"
)

set(_cpu_row_script "${_stage_dir}/cpu_row.lua")
file(WRITE "${_cpu_row_script}"
    "local idle = 0x${SYM_monitor_idle}\r\n"
    "local entry = 0x${SYM_test_cpu_row_output}\r\n"
    "local expected = ${_expected_count}\r\n"
    "local bytes = {}\r\n"
    "local phase = \"wait_reset\"\r\n"
    "local frames = 0\r\n"
    "local cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "local mem = cpu.spaces[\"program\"]\r\n"
    "mem:install_write_tap(${ACIA_DATA}, ${ACIA_DATA}, \"cpu_row_acia_data\", function(offset, data, mask)\r\n"
    "    table.insert(bytes, data & 0xff)\r\n"
    "end)\r\n"
    "local function hex_bytes()\r\n"
    "    local out = {}\r\n"
    "    for _,byte in ipairs(bytes) do table.insert(out, string.format(\"%02X\", byte)) end\r\n"
    "    return table.concat(out, \"\")\r\n"
    "end\r\n"
    "emu.register_frame_done(function()\r\n"
    "    frames = frames + 1\r\n"
    "    cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "    mem = cpu.spaces[\"program\"]\r\n"
    "    if phase == \"wait_reset\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 60 then return end\r\n"
    "        mem:write_u8(${ACIA_CONTROL}, 0x03)\r\n"
    "        mem:write_u8(${ACIA_CONTROL}, 0x15)\r\n"
    "        bytes = {}\r\n"
    "        cpu.state[\"PC\"].value = entry\r\n"
    "        phase = \"wait_output\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"wait_output\" then\r\n"
    "        if #bytes < expected and frames < 240 then return end\r\n"
    "        print(string.format(\"CPU_ROW COUNT=%d BYTES=%s\", #bytes, hex_bytes()))\r\n"
    "        manager.machine:exit()\r\n"
    "        return\r\n"
    "    end\r\n"
    "end, \"cpu_row\")\r\n"
)

execute_process(
    COMMAND
        "${_mame_exe}"
        m6805sbc
        -rompath roms
        -cfg_directory cfg
        -homepath .
        -video none
        -sound none
        -skip_gameinfo
        -nothrottle
        -autoboot_delay 0
        -autoboot_script cpu_row.lua
        -seconds_to_run 3
    WORKING_DIRECTORY "${_stage_dir}"
    RESULT_VARIABLE _mame_result
    OUTPUT_VARIABLE _mame_stdout
    ERROR_VARIABLE _mame_stderr
)

set(_mame_output "${_mame_stdout}\n${_mame_stderr}")

if(NOT _mame_result EQUAL 0)
    message(FATAL_ERROR "MAME failed with exit code ${_mame_result}\n${_mame_output}")
endif()

string(REGEX MATCH "CPU_ROW COUNT=([0-9]+) BYTES=([0-9A-Fa-f]*)" _output_match "${_mame_output}")
if(NOT _output_match)
    message(FATAL_ERROR "MAME output did not report CPU_ROW\n${_mame_output}")
endif()

set(_actual_count "${CMAKE_MATCH_1}")
set(_actual_bytes "${CMAKE_MATCH_2}")
string(TOUPPER "${_actual_bytes}" _actual_bytes)

if(NOT _actual_count STREQUAL "${_expected_count}")
    message(FATAL_ERROR "Expected ${_expected_count} CPU-row bytes, got ${_actual_count}\n${_mame_output}")
endif()

if(NOT _actual_bytes STREQUAL "${_expected_bytes}")
    message(FATAL_ERROR "Expected CPU-row bytes ${_expected_bytes}, got ${_actual_bytes}\n${_mame_output}")
endif()
