foreach(_required_var IN ITEMS MONITOR_BINARY MONITOR_SYMBOLS MONITOR_VERSION_TEXT MAME_EXE MAME_STAGE_DIR MONITOR_OUTPUT_DIR)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "${_required_var} is required")
    endif()
endforeach()

set(ACIA_DATA 0x0007)

get_filename_component(_monitor_binary "${MONITOR_BINARY}" ABSOLUTE)
get_filename_component(_monitor_symbols "${MONITOR_SYMBOLS}" ABSOLUTE)
get_filename_component(_mame_exe "${MAME_EXE}" ABSOLUTE)
get_filename_component(_monitor_output_dir "${MONITOR_OUTPUT_DIR}" ABSOLUTE)
get_filename_component(_stage_dir "${MAME_STAGE_DIR}" ABSOLUTE BASE_DIR "${_monitor_output_dir}")

if(NOT EXISTS "${_monitor_binary}")
    message(FATAL_ERROR "Monitor binary does not exist: ${_monitor_binary}")
endif()

if(NOT EXISTS "${_monitor_symbols}")
    message(FATAL_ERROR "Monitor symbols do not exist: ${_monitor_symbols}")
endif()

if(NOT EXISTS "${_mame_exe}")
    message(FATAL_ERROR "MAME executable does not exist: ${_mame_exe}")
endif()

file(TO_CMAKE_PATH "${_monitor_output_dir}" _monitor_output_cmp)
file(TO_CMAKE_PATH "${_stage_dir}" _stage_cmp)

if("${_stage_cmp}" STREQUAL "${_monitor_output_cmp}")
    message(FATAL_ERROR "MAME stage directory must not be the monitor output directory")
endif()

string(APPEND _monitor_output_cmp "/")
string(APPEND _stage_cmp "/")
string(FIND "${_stage_cmp}" "${_monitor_output_cmp}" _stage_prefix)
if(NOT _stage_prefix EQUAL 0)
    message(FATAL_ERROR "MAME stage directory must be under the monitor output directory: ${_stage_dir}")
endif()

function(_require_symbol _name)
    if(NOT DEFINED "SYM_${_name}")
        message(FATAL_ERROR "Missing symbol '${_name}' in ${_monitor_symbols}")
    endif()
endfunction()

file(STRINGS "${_monitor_symbols}" _symbol_lines)
foreach(_line IN LISTS _symbol_lines)
    if(_line MATCHES "^([A-Za-z_][A-Za-z0-9_]*)[ \t]+([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])")
        string(TOUPPER "${CMAKE_MATCH_2}" _symbol_value)
        set("SYM_${CMAKE_MATCH_1}" "${_symbol_value}")
    endif()
endforeach()

_require_symbol("monitor_idle")

string(ASCII 27 _esc)
string(ASCII 13 _cr)
string(ASCII 10 _lf)
set(_cpu_row "SP 007F  PC 1000  A 00  X 00  FLAGS 111 I     STOPPED: RESET")
string(LENGTH "${_cpu_row}" _cpu_row_length)
if(_cpu_row_length GREATER 67)
    message(FATAL_ERROR "CPU row must not overwrite columns 68 through 80: ${_cpu_row_length}")
endif()

set(_expected_text "${_esc}[H${_esc}[J${_esc}[68G${MONITOR_VERSION_TEXT}${_esc}[H${_cpu_row}${_cr}${_lf}")
string(HEX "${_expected_text}" _expected_bytes)
string(TOUPPER "${_expected_bytes}" _expected_bytes)
string(LENGTH "${_expected_bytes}" _expected_hex_length)
math(EXPR _expected_count "${_expected_hex_length} / 2")

file(REMOVE_RECURSE "${_stage_dir}")
file(MAKE_DIRECTORY
    "${_stage_dir}/roms/m6805sbc"
    "${_stage_dir}/cfg"
)

configure_file("${_monitor_binary}" "${_stage_dir}/roms/m6805sbc/rom1.bin" COPYONLY)
file(WRITE "${_stage_dir}/cfg/m6805sbc.cfg"
    "<?xml version=\"1.0\"?>\r\n"
    "<!-- This file is generated by the monitor MAME test. -->\r\n"
    "<mameconfig version=\"10\">\r\n"
    "    <system name=\"m6805sbc\">\r\n"
    "        <input>\r\n"
    "            <port tag=\":BAUD\" type=\"DIPSWITCH\" mask=\"3\" defvalue=\"0\" value=\"0\" />\r\n"
    "        </input>\r\n"
    "    </system>\r\n"
    "</mameconfig>\r\n"
)

set(_boot_script "${_stage_dir}/boot_screen.lua")
file(WRITE "${_boot_script}"
    "local idle = 0x${SYM_monitor_idle}\r\n"
    "local bytes = {}\r\n"
    "local frames = 0\r\n"
    "local phase = \"wait_idle\"\r\n"
    "local idle_frames = 0\r\n"
    "local idle_count = nil\r\n"
    "local cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "local mem = cpu.spaces[\"program\"]\r\n"
    "mem:install_write_tap(${ACIA_DATA}, ${ACIA_DATA}, \"boot_screen_acia_data\", function(offset, data, mask)\r\n"
    "    table.insert(bytes, data & 0xff)\r\n"
    "end)\r\n"
    "local function hex_bytes()\r\n"
    "    local out = {}\r\n"
    "    for _,byte in ipairs(bytes) do table.insert(out, string.format(\"%02X\", byte)) end\r\n"
    "    return table.concat(out, \"\")\r\n"
    "end\r\n"
    "emu.register_frame_done(function()\r\n"
    "    frames = frames + 1\r\n"
    "    cpu = manager.machine.devices[\":maincpu\"]\r\n"
    "    if phase == \"wait_idle\" then\r\n"
    "        if cpu.state[\"PC\"].value ~= idle and frames < 180 then return end\r\n"
    "        idle_count = #bytes\r\n"
    "        phase = \"settle_idle\"\r\n"
    "        return\r\n"
    "    end\r\n"
    "    if phase == \"settle_idle\" then\r\n"
    "        idle_frames = idle_frames + 1\r\n"
    "        if idle_frames < 20 and frames < 240 then return end\r\n"
    "        print(string.format(\"BOOT_SCREEN COUNT=%d IDLE_EXTRA=%d BYTES=%s\", #bytes, #bytes - idle_count, hex_bytes()))\r\n"
    "        manager.machine:exit()\r\n"
    "        return\r\n"
    "    end\r\n"
    "end, \"boot_screen\")\r\n"
)

execute_process(
    COMMAND
        "${_mame_exe}"
        m6805sbc
        -rompath roms
        -cfg_directory cfg
        -homepath .
        -video none
        -sound none
        -skip_gameinfo
        -nothrottle
        -autoboot_delay 0
        -autoboot_script boot_screen.lua
        -seconds_to_run 3
    WORKING_DIRECTORY "${_stage_dir}"
    RESULT_VARIABLE _mame_result
    OUTPUT_VARIABLE _mame_stdout
    ERROR_VARIABLE _mame_stderr
)

set(_mame_output "${_mame_stdout}\n${_mame_stderr}")

if(NOT _mame_result EQUAL 0)
    message(FATAL_ERROR "MAME failed with exit code ${_mame_result}\n${_mame_output}")
endif()

string(REGEX MATCH "BOOT_SCREEN COUNT=([0-9]+) IDLE_EXTRA=([0-9]+) BYTES=([0-9A-Fa-f]*)" _output_match "${_mame_output}")
if(NOT _output_match)
    message(FATAL_ERROR "MAME output did not report BOOT_SCREEN\n${_mame_output}")
endif()

set(_actual_count "${CMAKE_MATCH_1}")
set(_idle_extra "${CMAKE_MATCH_2}")
set(_actual_bytes "${CMAKE_MATCH_3}")
string(TOUPPER "${_actual_bytes}" _actual_bytes)

if(NOT _actual_count STREQUAL "${_expected_count}")
    message(FATAL_ERROR "Expected ${_expected_count} boot-screen bytes, got ${_actual_count}\n${_mame_output}")
endif()

if(NOT _actual_bytes STREQUAL "${_expected_bytes}")
    message(FATAL_ERROR "Expected boot-screen bytes ${_expected_bytes}, got ${_actual_bytes}\n${_mame_output}")
endif()

if(NOT _idle_extra STREQUAL "0")
    message(FATAL_ERROR "Expected no bytes after monitor_idle, got ${_idle_extra}\n${_mame_output}")
endif()
