if(NOT DEFINED MONITOR_SOURCE)
    message(FATAL_ERROR "MONITOR_SOURCE is required")
endif()

if(NOT EXISTS "${MONITOR_SOURCE}")
    message(FATAL_ERROR "monitor source does not exist: ${MONITOR_SOURCE}")
endif()

file(STRINGS "${MONITOR_SOURCE}" source_lines)

set(active_module "")
set(seen_modules "")
set(errors "")
set(line_no 0)

foreach(line IN LISTS source_lines)
    math(EXPR line_no "${line_no} + 1")

    if(line MATCHES "^[ \t]*\\.module[ \t]+([A-Za-z_][A-Za-z0-9_]*)")
        set(active_module "${CMAKE_MATCH_1}")
        list(APPEND seen_modules "${active_module}")
    endif()

    if(line MATCHES "^([A-Za-z_][A-Za-z0-9_]*):")
        set(label "${CMAKE_MATCH_1}")
        if(active_module STREQUAL "")
            list(APPEND errors "label '${label}' at line ${line_no} appears before any .module")
        endif()
        set("label_module_${label}" "${active_module}")
    endif()

    if(line MATCHES "^[ \t]*\\.org[ \t]+\\$1ff6")
        if(NOT active_module STREQUAL "interrupt_vectors")
            list(APPEND errors ".org $1ff6 at line ${line_no} must be in module 'interrupt_vectors'")
        endif()
    endif()
endforeach()

macro(require_module module)
    list(FIND seen_modules "${module}" module_index)
    if(module_index EQUAL -1)
        list(APPEND errors "missing required module '${module}'")
    endif()
endmacro()

macro(require_label_module label module)
    if(NOT DEFINED label_module_${label})
        list(APPEND errors "missing required label '${label}'")
    elseif(NOT "${label_module_${label}}" STREQUAL "${module}")
        list(APPEND errors "label '${label}' is in module '${label_module_${label}}', expected '${module}'")
    endif()
endmacro()

require_module("reset_entry")
require_module("interrupt_dispatch")
require_module("console_io")
require_module("draw_boot_screen")
require_module("draw_cpu_row")
require_module("screen_output")
require_module("disasm_output")
require_module("hex_output")
require_module("draw_memory_row")
require_module("draw_disassembly_row")
require_module("memory_panel")
require_module("memory_editing")
require_module("memory_cursor")
require_module("test_hooks")
require_module("monitor_idle")
require_module("data_tables")

require_label_module("reset_entry" "reset_entry")
require_label_module("swi_entry" "interrupt_dispatch")
require_label_module("timer_dispatch" "interrupt_dispatch")
require_label_module("external_dispatch" "interrupt_dispatch")
require_label_module("init_console" "console_io")
require_label_module("chrout" "console_io")
require_label_module("draw_boot_screen" "draw_boot_screen")
require_label_module("draw_cpu_row" "draw_cpu_row")
require_label_module("emit_spaces" "screen_output")
require_label_module("decode_inst" "disasm_output")
require_label_module("disassemble_line" "disasm_output")
require_label_module("emit_hex_byte" "hex_output")
require_label_module("draw_memory_row" "draw_memory_row")
require_label_module("draw_disassembly_row" "draw_disassembly_row")
require_label_module("init_memory_panel" "memory_panel")
require_label_module("memory_key_input" "memory_editing")
require_label_module("memory_select_cursor" "memory_cursor")
require_label_module("memory_cursor_left" "memory_cursor")
require_label_module("test_console_output" "test_hooks")
require_label_module("test_cpu_row_output" "test_hooks")
require_label_module("monitor_idle" "monitor_idle")
require_label_module("hex_digits" "data_tables")
require_label_module("boot_screen_text" "data_tables")

if(errors)
    list(JOIN errors "\n  - " error_text)
    message(FATAL_ERROR "monitor.asm source structure failed:\n  - ${error_text}")
endif()
